-- =====================================================================
--  Projetos: TIPO_PROJETO + MODALIDADE + SEM_CONTRATO e o checklist de
--  documentos que sai dessa combinacao, mais os campos de integracao do
--  recebimento (SAP CRM / SAP CCS / SharePoint / esteira de analise).
--
--  Fluxo do recebimento (o que o colaborador faz a partir do e-mail):
--    1. interpreta o e-mail do provedor e classifica o TIPO_PROJETO
--    2. cria o protocolo no SAP CRM            -> PROTOCOLO_SAP_CRM
--    3. a nota associada e gerada no SAP CCS   -> NOTA_SAP_CCS
--    4. salva os documentos na pasta do SharePoint do sistema -> PASTA_SHAREPOINT
--    5. o projeto entra na esteira de analise ja existente
--
--  Rodar DEPOIS de sql/PORTAL_COMPARTILHAMENTO_PROJETO.sql.
--  Schema de trabalho: ajuste "CLB349328" se o seu for outro.
-- =====================================================================


-- ---------------------------------------------------------------------
-- 1) Novas colunas em PROJETO
-- ---------------------------------------------------------------------
ALTER TABLE "CLB349328"."PORTAL_COMPARTILHAMENTO_PROJETO" ADD (
    "TIPO_PROJETO"            NVARCHAR(30),                 -- NOVO_COMPARTILHAMENTO | PONTOS_REVELIA | REMOCAO_PONTOS
    "MODALIDADE"             NVARCHAR(24)  DEFAULT 'COMPLETO', -- COMPLETO | CHECKLIST_SIMPLIFICADO
    "SEM_CONTRATO"           NVARCHAR(1)   DEFAULT 'N',      -- provedor ainda sem contrato -> exige documentacao societaria
    "DIAS_OPERACAO_REVELIA"  INTEGER,                        -- ha quantos dias a ocupacao a revelia opera (regra do Checklist Simplificado)

    -- Integracao do recebimento
    "PROTOCOLO_SAP_CRM"      NVARCHAR(40),
    "NOTA_SAP_CCS"           NVARCHAR(40),
    "PASTA_SHAREPOINT"       NVARCHAR(1000),

    -- Checklist de etapas do recebimento (marcadas manualmente)
    "ETAPA_PROTOCOLO_CRM"    NVARCHAR(1)   DEFAULT 'N',
    "ETAPA_NOTA_CCS"         NVARCHAR(1)   DEFAULT 'N',
    "ETAPA_PASTA_SHAREPOINT" NVARCHAR(1)   DEFAULT 'N',
    "ETAPA_ESTEIRA_ANALISE"  NVARCHAR(1)   DEFAULT 'N'
);

CREATE INDEX "IX_PROJETO_TIPO" ON "CLB349328"."PORTAL_COMPARTILHAMENTO_PROJETO" ("TIPO_PROJETO");


-- ---------------------------------------------------------------------
-- 2) Catalogo de TIPOS DE PROJETO
-- ---------------------------------------------------------------------
CREATE COLUMN TABLE "CLB349328"."PORTAL_COMPARTILHAMENTO_PROJETO_TIPO"
(
    "CODIGO"     NVARCHAR(30)  NOT NULL,
    "NOME"       NVARCHAR(120) NOT NULL,
    "DESCRICAO"  NVARCHAR(600),
    "ORDEM"      INTEGER DEFAULT 0,
    "ATIVO"      NVARCHAR(1) DEFAULT 'S',
    PRIMARY KEY ("CODIGO")
)
UNLOAD PRIORITY 5 AUTO MERGE;

INSERT INTO "CLB349328"."PORTAL_COMPARTILHAMENTO_PROJETO_TIPO" ("CODIGO","NOME","DESCRICAO","ORDEM","ATIVO") VALUES
 ('NOVO_COMPARTILHAMENTO','Serviço de Novo Compartilhamento',
  'Projeto de rede nova a ser instalada na infraestrutura da distribuidora. Exige a documentacao tecnica e ambiental completa.',10,'S');
INSERT INTO "CLB349328"."PORTAL_COMPARTILHAMENTO_PROJETO_TIPO" ("CODIGO","NOME","DESCRICAO","ORDEM","ATIVO") VALUES
 ('PONTOS_REVELIA','Pontos à Revelia',
  'Regularizacao de ocupacao ja existente que foi instalada sem cadastro previo. Nao exige planta detalhada nem carta ambiental.',20,'S');
INSERT INTO "CLB349328"."PORTAL_COMPARTILHAMENTO_PROJETO_TIPO" ("CODIGO","NOME","DESCRICAO","ORDEM","ATIVO") VALUES
 ('REMOCAO_PONTOS','Remoção de Pontos',
  'Desmobilizacao de ocupacao existente. Exige cronograma de desmobilizacao no lugar da carta de rede instalada.',30,'S');


-- ---------------------------------------------------------------------
-- 3) Catalogo de MODALIDADES de apresentacao
-- ---------------------------------------------------------------------
CREATE COLUMN TABLE "CLB349328"."PORTAL_COMPARTILHAMENTO_PROJETO_MODALIDADE"
(
    "CODIGO"              NVARCHAR(24)  NOT NULL,
    "NOME"                NVARCHAR(120) NOT NULL,
    "DESCRICAO"           NVARCHAR(600),
    "REGRA_ELEGIBILIDADE" NVARCHAR(600),
    "ORDEM"               INTEGER DEFAULT 0,
    "ATIVO"               NVARCHAR(1) DEFAULT 'S',
    PRIMARY KEY ("CODIGO")
)
UNLOAD PRIORITY 5 AUTO MERGE;

INSERT INTO "CLB349328"."PORTAL_COMPARTILHAMENTO_PROJETO_MODALIDADE" ("CODIGO","NOME","DESCRICAO","REGRA_ELEGIBILIDADE","ORDEM","ATIVO") VALUES
 ('COMPLETO','Documentação completa','Fluxo padrao: o provedor envia toda a lista de documentos obrigatorios do tipo de projeto.',NULL,10,'S');
INSERT INTO "CLB349328"."PORTAL_COMPARTILHAMENTO_PROJETO_MODALIDADE" ("CODIGO","NOME","DESCRICAO","REGRA_ELEGIBILIDADE","ORDEM","ATIVO") VALUES
 ('CHECKLIST_SIMPLIFICADO','Checklist Simplificado',
  'Apresentacao com lista reduzida de documentos. Segue o fluxo normal dentro do Portal.',
  'Valido apenas se: (I) projeto com ocupacao a partir de 300 pontos novos; OU (II) regularizacao de ocupacao a revelia operacionalizada ha no minimo 180 dias.',20,'S');


-- ---------------------------------------------------------------------
-- 4) Reseed do catalogo de TIPOS DE DOCUMENTO (norma vigente)
--    Substitui o seed antigo de PROJETO_TIPO_DOCUMENTO.
-- ---------------------------------------------------------------------
DELETE FROM "CLB349328"."PORTAL_COMPARTILHAMENTO_PROJETO_TIPO_DOCUMENTO";

INSERT INTO "CLB349328"."PORTAL_COMPARTILHAMENTO_PROJETO_TIPO_DOCUMENTO" ("CODIGO","NOME","DESCRICAO","OBRIGATORIO","EXTENSOES_ACEITAS","ORDEM","ATIVO","CREATED_AT") VALUES
 ('SOLICITACAO_ANALISE','Solicitação de análise','Carta/oficio do provedor solicitando a analise do projeto.','S','pdf',10,'S',CURRENT_UTCTIMESTAMP);
INSERT INTO "CLB349328"."PORTAL_COMPARTILHAMENTO_PROJETO_TIPO_DOCUMENTO" ("CODIGO","NOME","DESCRICAO","OBRIGATORIO","EXTENSOES_ACEITAS","ORDEM","ATIVO","CREATED_AT") VALUES
 ('KMZ','Arquivo KMZ','Tracado georreferenciado do projeto.','S','kmz,kml',20,'S',CURRENT_UTCTIMESTAMP);
INSERT INTO "CLB349328"."PORTAL_COMPARTILHAMENTO_PROJETO_TIPO_DOCUMENTO" ("CODIGO","NOME","DESCRICAO","OBRIGATORIO","EXTENSOES_ACEITAS","ORDEM","ATIVO","CREATED_AT") VALUES
 ('ART_RRT_TRT','ART, RRT ou TRT','Anotacao / Registro / Termo de Responsabilidade Tecnica do responsavel.','S','pdf',30,'S',CURRENT_UTCTIMESTAMP);
INSERT INTO "CLB349328"."PORTAL_COMPARTILHAMENTO_PROJETO_TIPO_DOCUMENTO" ("CODIGO","NOME","DESCRICAO","OBRIGATORIO","EXTENSOES_ACEITAS","ORDEM","ATIVO","CREATED_AT") VALUES
 ('PLANILHA_POSTES','Planilha de Postes','Relacao dos postes com identificador, latitude e longitude.','S','xlsx,csv',40,'S',CURRENT_UTCTIMESTAMP);
INSERT INTO "CLB349328"."PORTAL_COMPARTILHAMENTO_PROJETO_TIPO_DOCUMENTO" ("CODIGO","NOME","DESCRICAO","OBRIGATORIO","EXTENSOES_ACEITAS","ORDEM","ATIVO","CREATED_AT") VALUES
 ('PLANTA_DETALHADA','Planta detalhada','Planta do projeto com detalhamento da rede.','S','pdf,dwg',50,'S',CURRENT_UTCTIMESTAMP);
INSERT INTO "CLB349328"."PORTAL_COMPARTILHAMENTO_PROJETO_TIPO_DOCUMENTO" ("CODIGO","NOME","DESCRICAO","OBRIGATORIO","EXTENSOES_ACEITAS","ORDEM","ATIVO","CREATED_AT") VALUES
 ('MEMORIAL_TECNICO','Memorial Técnico descritivo e de cálculo','Memorial descritivo e de calculo da rede.','S','pdf',60,'S',CURRENT_UTCTIMESTAMP);
INSERT INTO "CLB349328"."PORTAL_COMPARTILHAMENTO_PROJETO_TIPO_DOCUMENTO" ("CODIGO","NOME","DESCRICAO","OBRIGATORIO","EXTENSOES_ACEITAS","ORDEM","ATIVO","CREATED_AT") VALUES
 ('CARTA_REDE_INSTALADA','Carta de Rede Instalada','Declaracao da rede instalada.','S','pdf',70,'S',CURRENT_UTCTIMESTAMP);
INSERT INTO "CLB349328"."PORTAL_COMPARTILHAMENTO_PROJETO_TIPO_DOCUMENTO" ("CODIGO","NOME","DESCRICAO","OBRIGATORIO","EXTENSOES_ACEITAS","ORDEM","ATIVO","CREATED_AT") VALUES
 ('CARTA_AMBIENTAL','Carta de Conformidade Ambiental','Declaracao de conformidade ambiental.','S','pdf',80,'S',CURRENT_UTCTIMESTAMP);
INSERT INTO "CLB349328"."PORTAL_COMPARTILHAMENTO_PROJETO_TIPO_DOCUMENTO" ("CODIGO","NOME","DESCRICAO","OBRIGATORIO","EXTENSOES_ACEITAS","ORDEM","ATIVO","CREATED_AT") VALUES
 ('CRONOGRAMA_DESMOBILIZACAO','Cronograma de desmobilização','Cronograma de retirada dos pontos.','S','pdf,xlsx',90,'S',CURRENT_UTCTIMESTAMP);
INSERT INTO "CLB349328"."PORTAL_COMPARTILHAMENTO_PROJETO_TIPO_DOCUMENTO" ("CODIGO","NOME","DESCRICAO","OBRIGATORIO","EXTENSOES_ACEITAS","ORDEM","ATIVO","CREATED_AT") VALUES
 ('CHECKLIST_SIMPLIFICADO','Checklist Simplificado','Formulario de checklist simplificado preenchido.','S','pdf,xlsx',100,'S',CURRENT_UTCTIMESTAMP);
-- Documentacao societaria (so quando SEM_CONTRATO = 'S')
INSERT INTO "CLB349328"."PORTAL_COMPARTILHAMENTO_PROJETO_TIPO_DOCUMENTO" ("CODIGO","NOME","DESCRICAO","OBRIGATORIO","EXTENSOES_ACEITAS","ORDEM","ATIVO","CREATED_AT") VALUES
 ('CONTRATO_SOCIAL','Contrato Social da Empresa e Alterações','Contrato social vigente e todas as alteracoes.','S','pdf',110,'S',CURRENT_UTCTIMESTAMP);
INSERT INTO "CLB349328"."PORTAL_COMPARTILHAMENTO_PROJETO_TIPO_DOCUMENTO" ("CODIGO","NOME","DESCRICAO","OBRIGATORIO","EXTENSOES_ACEITAS","ORDEM","ATIVO","CREATED_AT") VALUES
 ('CARTAO_CNPJ','Cartão CNPJ','Comprovante de inscricao e situacao cadastral (Receita Federal).','S','pdf',120,'S',CURRENT_UTCTIMESTAMP);
INSERT INTO "CLB349328"."PORTAL_COMPARTILHAMENTO_PROJETO_TIPO_DOCUMENTO" ("CODIGO","NOME","DESCRICAO","OBRIGATORIO","EXTENSOES_ACEITAS","ORDEM","ATIVO","CREATED_AT") VALUES
 ('OUTORGA_ANATEL','Termo de Outorga ou Dispensa da Anatel','Outorga SCM/SLP ou dispensa da Anatel.','S','pdf',130,'S',CURRENT_UTCTIMESTAMP);
INSERT INTO "CLB349328"."PORTAL_COMPARTILHAMENTO_PROJETO_TIPO_DOCUMENTO" ("CODIGO","NOME","DESCRICAO","OBRIGATORIO","EXTENSOES_ACEITAS","ORDEM","ATIVO","CREATED_AT") VALUES
 ('DOC_REP_LEGAL','CNH ou documento oficial com foto do representante legal','Documento com foto que conste o CPF do representante legal.','S','pdf,jpg,png',140,'S',CURRENT_UTCTIMESTAMP);
INSERT INTO "CLB349328"."PORTAL_COMPARTILHAMENTO_PROJETO_TIPO_DOCUMENTO" ("CODIGO","NOME","DESCRICAO","OBRIGATORIO","EXTENSOES_ACEITAS","ORDEM","ATIVO","CREATED_AT") VALUES
 ('FORMULARIO_CADASTRAL','Formulário de dados Cadastrais','Formulario preenchido com os dados do representante legal e da testemunha, para assinatura da minuta contratual.','S','pdf,docx',150,'S',CURRENT_UTCTIMESTAMP);


-- ---------------------------------------------------------------------
-- 5) MATRIZ: quais documentos cada combinacao exige
--    CHAVE = TIPO_PROJETO | 'CHECKLIST_SIMPLIFICADO' | 'SEM_CONTRATO'
--
--    Resolucao do checklist de um projeto:
--      - MODALIDADE = COMPLETO           -> pega as linhas da CHAVE = TIPO_PROJETO
--      - MODALIDADE = CHECKLIST_SIMPLIFICADO -> pega as linhas da CHAVE = 'CHECKLIST_SIMPLIFICADO'
--      - SEM_CONTRATO = 'S'              -> ACRESCENTA as linhas da CHAVE = 'SEM_CONTRATO'
-- ---------------------------------------------------------------------
CREATE COLUMN TABLE "CLB349328"."PORTAL_COMPARTILHAMENTO_PROJETO_TIPO_DOC"
(
    "ID"           INTEGER CS_INT GENERATED BY DEFAULT AS IDENTITY,
    "CHAVE"        NVARCHAR(30)  NOT NULL,
    "CODIGO_DOC"   NVARCHAR(40)  NOT NULL,   -- -> PROJETO_TIPO_DOCUMENTO.CODIGO
    "OBRIGATORIO"  NVARCHAR(1)   DEFAULT 'S',
    "ORDEM"        INTEGER DEFAULT 0,
    "ATIVO"        NVARCHAR(1)   DEFAULT 'S',
    PRIMARY KEY ("ID")
)
UNLOAD PRIORITY 5 AUTO MERGE;

CREATE UNIQUE INDEX "IX_PROJTIPODOC_CHAVE_DOC"
    ON "CLB349328"."PORTAL_COMPARTILHAMENTO_PROJETO_TIPO_DOC" ("CHAVE","CODIGO_DOC");

-- Novo Compartilhamento
INSERT INTO "CLB349328"."PORTAL_COMPARTILHAMENTO_PROJETO_TIPO_DOC" ("CHAVE","CODIGO_DOC","OBRIGATORIO","ORDEM") VALUES ('NOVO_COMPARTILHAMENTO','SOLICITACAO_ANALISE','S',10);
INSERT INTO "CLB349328"."PORTAL_COMPARTILHAMENTO_PROJETO_TIPO_DOC" ("CHAVE","CODIGO_DOC","OBRIGATORIO","ORDEM") VALUES ('NOVO_COMPARTILHAMENTO','KMZ','S',20);
INSERT INTO "CLB349328"."PORTAL_COMPARTILHAMENTO_PROJETO_TIPO_DOC" ("CHAVE","CODIGO_DOC","OBRIGATORIO","ORDEM") VALUES ('NOVO_COMPARTILHAMENTO','ART_RRT_TRT','S',30);
INSERT INTO "CLB349328"."PORTAL_COMPARTILHAMENTO_PROJETO_TIPO_DOC" ("CHAVE","CODIGO_DOC","OBRIGATORIO","ORDEM") VALUES ('NOVO_COMPARTILHAMENTO','PLANILHA_POSTES','S',40);
INSERT INTO "CLB349328"."PORTAL_COMPARTILHAMENTO_PROJETO_TIPO_DOC" ("CHAVE","CODIGO_DOC","OBRIGATORIO","ORDEM") VALUES ('NOVO_COMPARTILHAMENTO','PLANTA_DETALHADA','S',50);
INSERT INTO "CLB349328"."PORTAL_COMPARTILHAMENTO_PROJETO_TIPO_DOC" ("CHAVE","CODIGO_DOC","OBRIGATORIO","ORDEM") VALUES ('NOVO_COMPARTILHAMENTO','MEMORIAL_TECNICO','S',60);
INSERT INTO "CLB349328"."PORTAL_COMPARTILHAMENTO_PROJETO_TIPO_DOC" ("CHAVE","CODIGO_DOC","OBRIGATORIO","ORDEM") VALUES ('NOVO_COMPARTILHAMENTO','CARTA_REDE_INSTALADA','S',70);
INSERT INTO "CLB349328"."PORTAL_COMPARTILHAMENTO_PROJETO_TIPO_DOC" ("CHAVE","CODIGO_DOC","OBRIGATORIO","ORDEM") VALUES ('NOVO_COMPARTILHAMENTO','CARTA_AMBIENTAL','S',80);

-- Pontos a Revelia
INSERT INTO "CLB349328"."PORTAL_COMPARTILHAMENTO_PROJETO_TIPO_DOC" ("CHAVE","CODIGO_DOC","OBRIGATORIO","ORDEM") VALUES ('PONTOS_REVELIA','SOLICITACAO_ANALISE','S',10);
INSERT INTO "CLB349328"."PORTAL_COMPARTILHAMENTO_PROJETO_TIPO_DOC" ("CHAVE","CODIGO_DOC","OBRIGATORIO","ORDEM") VALUES ('PONTOS_REVELIA','KMZ','S',20);
INSERT INTO "CLB349328"."PORTAL_COMPARTILHAMENTO_PROJETO_TIPO_DOC" ("CHAVE","CODIGO_DOC","OBRIGATORIO","ORDEM") VALUES ('PONTOS_REVELIA','ART_RRT_TRT','S',30);
INSERT INTO "CLB349328"."PORTAL_COMPARTILHAMENTO_PROJETO_TIPO_DOC" ("CHAVE","CODIGO_DOC","OBRIGATORIO","ORDEM") VALUES ('PONTOS_REVELIA','PLANILHA_POSTES','S',40);
INSERT INTO "CLB349328"."PORTAL_COMPARTILHAMENTO_PROJETO_TIPO_DOC" ("CHAVE","CODIGO_DOC","OBRIGATORIO","ORDEM") VALUES ('PONTOS_REVELIA','MEMORIAL_TECNICO','S',50);
INSERT INTO "CLB349328"."PORTAL_COMPARTILHAMENTO_PROJETO_TIPO_DOC" ("CHAVE","CODIGO_DOC","OBRIGATORIO","ORDEM") VALUES ('PONTOS_REVELIA','CARTA_REDE_INSTALADA','S',60);

-- Remocao de Pontos
INSERT INTO "CLB349328"."PORTAL_COMPARTILHAMENTO_PROJETO_TIPO_DOC" ("CHAVE","CODIGO_DOC","OBRIGATORIO","ORDEM") VALUES ('REMOCAO_PONTOS','SOLICITACAO_ANALISE','S',10);
INSERT INTO "CLB349328"."PORTAL_COMPARTILHAMENTO_PROJETO_TIPO_DOC" ("CHAVE","CODIGO_DOC","OBRIGATORIO","ORDEM") VALUES ('REMOCAO_PONTOS','KMZ','S',20);
INSERT INTO "CLB349328"."PORTAL_COMPARTILHAMENTO_PROJETO_TIPO_DOC" ("CHAVE","CODIGO_DOC","OBRIGATORIO","ORDEM") VALUES ('REMOCAO_PONTOS','ART_RRT_TRT','S',30);
INSERT INTO "CLB349328"."PORTAL_COMPARTILHAMENTO_PROJETO_TIPO_DOC" ("CHAVE","CODIGO_DOC","OBRIGATORIO","ORDEM") VALUES ('REMOCAO_PONTOS','PLANILHA_POSTES','S',40);
INSERT INTO "CLB349328"."PORTAL_COMPARTILHAMENTO_PROJETO_TIPO_DOC" ("CHAVE","CODIGO_DOC","OBRIGATORIO","ORDEM") VALUES ('REMOCAO_PONTOS','MEMORIAL_TECNICO','S',50);
INSERT INTO "CLB349328"."PORTAL_COMPARTILHAMENTO_PROJETO_TIPO_DOC" ("CHAVE","CODIGO_DOC","OBRIGATORIO","ORDEM") VALUES ('REMOCAO_PONTOS','CRONOGRAMA_DESMOBILIZACAO','S',60);

-- Checklist Simplificado (independe do tipo)
INSERT INTO "CLB349328"."PORTAL_COMPARTILHAMENTO_PROJETO_TIPO_DOC" ("CHAVE","CODIGO_DOC","OBRIGATORIO","ORDEM") VALUES ('CHECKLIST_SIMPLIFICADO','CHECKLIST_SIMPLIFICADO','S',10);
INSERT INTO "CLB349328"."PORTAL_COMPARTILHAMENTO_PROJETO_TIPO_DOC" ("CHAVE","CODIGO_DOC","OBRIGATORIO","ORDEM") VALUES ('CHECKLIST_SIMPLIFICADO','ART_RRT_TRT','S',20);
INSERT INTO "CLB349328"."PORTAL_COMPARTILHAMENTO_PROJETO_TIPO_DOC" ("CHAVE","CODIGO_DOC","OBRIGATORIO","ORDEM") VALUES ('CHECKLIST_SIMPLIFICADO','KMZ','S',30);
INSERT INTO "CLB349328"."PORTAL_COMPARTILHAMENTO_PROJETO_TIPO_DOC" ("CHAVE","CODIGO_DOC","OBRIGATORIO","ORDEM") VALUES ('CHECKLIST_SIMPLIFICADO','CARTA_REDE_INSTALADA','S',40);

-- Empresa sem contrato (ACRESCENTA a qualquer combinacao)
INSERT INTO "CLB349328"."PORTAL_COMPARTILHAMENTO_PROJETO_TIPO_DOC" ("CHAVE","CODIGO_DOC","OBRIGATORIO","ORDEM") VALUES ('SEM_CONTRATO','CONTRATO_SOCIAL','S',10);
INSERT INTO "CLB349328"."PORTAL_COMPARTILHAMENTO_PROJETO_TIPO_DOC" ("CHAVE","CODIGO_DOC","OBRIGATORIO","ORDEM") VALUES ('SEM_CONTRATO','CARTAO_CNPJ','S',20);
INSERT INTO "CLB349328"."PORTAL_COMPARTILHAMENTO_PROJETO_TIPO_DOC" ("CHAVE","CODIGO_DOC","OBRIGATORIO","ORDEM") VALUES ('SEM_CONTRATO','OUTORGA_ANATEL','S',30);
INSERT INTO "CLB349328"."PORTAL_COMPARTILHAMENTO_PROJETO_TIPO_DOC" ("CHAVE","CODIGO_DOC","OBRIGATORIO","ORDEM") VALUES ('SEM_CONTRATO','DOC_REP_LEGAL','S',40);
INSERT INTO "CLB349328"."PORTAL_COMPARTILHAMENTO_PROJETO_TIPO_DOC" ("CHAVE","CODIGO_DOC","OBRIGATORIO","ORDEM") VALUES ('SEM_CONTRATO','FORMULARIO_CADASTRAL','S',50);


-- =====================================================================
--  Dominios adicionais (validados no backend):
--    PROJETO.TIPO_PROJETO : NOVO_COMPARTILHAMENTO | PONTOS_REVELIA | REMOCAO_PONTOS
--    PROJETO.MODALIDADE   : COMPLETO | CHECKLIST_SIMPLIFICADO
--    PROJETO.SEM_CONTRATO : S | N
--
--  Regra do Checklist Simplificado (bloqueia a criacao se nao atender):
--    QTD_POSTES_INFORMADA >= 300
--    OU (TIPO_PROJETO = 'PONTOS_REVELIA' E DIAS_OPERACAO_REVELIA >= 180)
-- =====================================================================
