-- =====================================================================
--  Interações de contato da Jornada de Entrantes
--  Tabela PORTAL_COMPARTILHAMENTO_ENTRADA_INTERACAO
--
--  Contexto
--  --------
--  A tela de detalhe do entrante mostra uma "Timeline do Entrante" que
--  junta, em ordem cronológica:
--    - as transições de estágio (PORTAL_COMPARTILHAMENTO_HISTORICO_ENTRADA)
--    - as interações de contato registradas pelo time comercial
--      (e-mail encaminhado, ligação, WhatsApp, reunião, visita).
--  Esta tabela guarda o segundo grupo.
--
--  Padrão do projeto:
--    - CREATE COLUMN TABLE ... UNLOAD PRIORITY 5 AUTO MERGE
--    - PK INTEGER CS_INT GENERATED BY DEFAULT AS IDENTITY
--    - texto NVARCHAR(n); data/hora LONGDATE CS_LONGDATE
--    - SEM foreign key / check constraint: os domínios são validados no
--      backend (routers/entrantes.py), como em HISTORICO_ENTRADA.
--
--  Schema de trabalho: ajuste "CLB349328" se o seu for outro.
-- =====================================================================

CREATE COLUMN TABLE "CLB349328"."PORTAL_COMPARTILHAMENTO_ENTRADA_INTERACAO"
(
    "ID_INTERACAO"    INTEGER CS_INT GENERATED BY DEFAULT AS IDENTITY,
    "ID_ENTRADA"      INTEGER       NOT NULL,          -- -> PORTAL_COMPARTILHAMENTO_ENTRADA.ID_ENTRADA

    "CANAL"           NVARCHAR(20)  NOT NULL,          -- EMAIL | LIGACAO | WHATSAPP | REUNIAO | PRESENCIAL | OUTRO
    "SENTIDO"         NVARCHAR(10)  DEFAULT 'ENVIADO', -- ENVIADO | RECEBIDO

    "CONTATO"         NVARCHAR(200),                   -- e-mail / telefone / pessoa com quem foi o contato
    "ASSUNTO"         NVARCHAR(300),                   -- resumo em uma linha
    "OBSERVACAO"      NVARCHAR(4000),                  -- o que foi tratado, próximos passos

    "USUARIO"         NVARCHAR(100),                   -- quem registrou (login do portal)
    "DATA_INTERACAO"  LONGDATE CS_LONGDATE,

    PRIMARY KEY ("ID_INTERACAO")
)
UNLOAD PRIORITY 5 AUTO MERGE;

CREATE INDEX "IX_ENTINT_ENTRADA" ON "CLB349328"."PORTAL_COMPARTILHAMENTO_ENTRADA_INTERACAO" ("ID_ENTRADA");
CREATE INDEX "IX_ENTINT_DATA"    ON "CLB349328"."PORTAL_COMPARTILHAMENTO_ENTRADA_INTERACAO" ("DATA_INTERACAO");


-- ---------------------------------------------------------------------
--  Domínios de valores (validados no backend, não por constraint):
--
--  CANAL   : EMAIL | LIGACAO | WHATSAPP | REUNIAO | PRESENCIAL | OUTRO
--  SENTIDO : ENVIADO | RECEBIDO
-- ---------------------------------------------------------------------

-- Conferência:
--   SELECT "CANAL", COUNT(*) FROM "CLB349328"."PORTAL_COMPARTILHAMENTO_ENTRADA_INTERACAO"
--    GROUP BY "CANAL" ORDER BY "CANAL";
-- =====================================================================
