-- =====================================================================
--  Carteira de Serviço das Equipes de Campo
--
--  Um "gerador de carteira" monta o roteiro de trabalho das equipes de
--  campo (diária / semanal / mensal). Os postes podem ser escolhidos a
--  mão OU gerados automaticamente por uma das ESTRATÉGIAS (lógicas de
--  priorização - ver PORTAL_COMPARTILHAMENTO_CARTEIRA_ESTRATEGIA).
--
--  A alocação respeita:
--   - EPS e equipes escolhidas
--   - quantidade de postes por dia
--   - município(s) / localidade(s) de atuação
--   - otimização de rota na semana: a equipe não pula de município a cada
--     dia; consome um município antes de ir para o próximo, e a ordem dos
--     postes no dia segue vizinho-mais-próximo.
--
--  Schema de trabalho: ajuste "CLB349328" se o seu for outro.
-- =====================================================================


-- ---------------------------------------------------------------------
-- 1) EPS (Empresa Prestadora de Serviço)
-- ---------------------------------------------------------------------
CREATE COLUMN TABLE "CLB349328"."PORTAL_COMPARTILHAMENTO_EPS"
(
    "ID_EPS"        INTEGER CS_INT GENERATED BY DEFAULT AS IDENTITY,
    "NOME"          NVARCHAR(150) NOT NULL,
    "CNPJ"          NVARCHAR(20),
    "TIPO_SERVICO"  NVARCHAR(20) DEFAULT 'AMBOS',   -- FISCALIZACAO | REMOCAO | AMBOS
    "ATIVO"         NVARCHAR(1)  DEFAULT 'S',
    "CREATED_AT"    LONGDATE CS_LONGDATE,
    PRIMARY KEY ("ID_EPS")
)
UNLOAD PRIORITY 5 AUTO MERGE;


-- ---------------------------------------------------------------------
-- 2) EQUIPE DE CAMPO
-- ---------------------------------------------------------------------
CREATE COLUMN TABLE "CLB349328"."PORTAL_COMPARTILHAMENTO_EQUIPE_CAMPO"
(
    "ID_EQUIPE"      INTEGER CS_INT GENERATED BY DEFAULT AS IDENTITY,
    "ID_EPS"         INTEGER NOT NULL,
    "NOME"           NVARCHAR(80) NOT NULL,          -- ex.: "Turma A"
    "ENCARREGADO"    NVARCHAR(120),
    "MUNICIPIO_BASE" NVARCHAR(120),                  -- ponto de partida da rota
    "LATITUDE_BASE"  DECIMAL(18,10),
    "LONGITUDE_BASE" DECIMAL(18,10),
    "TIPO"           NVARCHAR(20) DEFAULT 'FISCALIZACAO', -- FISCALIZACAO | REMOCAO
    "ATIVO"          NVARCHAR(1)  DEFAULT 'S',
    "CREATED_AT"     LONGDATE CS_LONGDATE,
    PRIMARY KEY ("ID_EQUIPE")
)
UNLOAD PRIORITY 5 AUTO MERGE;

CREATE INDEX "IX_EQUIPECAMPO_EPS" ON "CLB349328"."PORTAL_COMPARTILHAMENTO_EQUIPE_CAMPO" ("ID_EPS");


-- ---------------------------------------------------------------------
-- 3) CATÁLOGO DE ESTRATÉGIAS (lógicas de geração automática)
--    Cada uma tem uma legenda explicativa mostrada no gerador.
-- ---------------------------------------------------------------------
CREATE COLUMN TABLE "CLB349328"."PORTAL_COMPARTILHAMENTO_CARTEIRA_ESTRATEGIA"
(
    "CODIGO"      NVARCHAR(40) NOT NULL,
    "NOME"        NVARCHAR(120) NOT NULL,
    "DESCRICAO"   NVARCHAR(1000),                    -- legenda explicativa
    "PARAMETROS"  NVARCHAR(500),                     -- parâmetros aceitos (raio_m, limiar, etc.)
    "ORDEM"       INTEGER DEFAULT 0,
    "ATIVO"       NVARCHAR(1) DEFAULT 'S',
    PRIMARY KEY ("CODIGO")
)
UNLOAD PRIORITY 5 AUTO MERGE;

INSERT INTO "CLB349328"."PORTAL_COMPARTILHAMENTO_CARTEIRA_ESTRATEGIA" ("CODIGO","NOME","DESCRICAO","PARAMETROS","ORDEM","ATIVO") VALUES
 ('VAO_ENTRE_PROVEDORES','Vão sem provedor entre postes com provedor',
  'Seleciona postes SEM provedor cercados por postes COM provedor (num raio de rua). Ex.: num corredor de postes, se entre dois com provedor há um sem, há forte indício de ocupação não cadastrada nesse poste. É a lógica de maior evidência.',
  'raio_m (padrão 60), min_vizinhos_com_provedor (padrão 2), limiar_fracao (padrão 0.5)',10,'S');
INSERT INTO "CLB349328"."PORTAL_COMPARTILHAMENTO_CARTEIRA_ESTRATEGIA" ("CODIGO","NOME","DESCRICAO","PARAMETROS","ORDEM","ATIVO") VALUES
 ('CORREDOR_MISTO','Corredores com postes com e sem provedor',
  'Agrupa os postes em trechos de ~150 m. Prioriza os SEM provedor que estão em trechos onde também existem postes COM provedor - provável expansão de rede de um ISP sem declarar todos os pontos.',
  'celula_m (padrão 150)',20,'S');
INSERT INTO "CLB349328"."PORTAL_COMPARTILHAMENTO_CARTEIRA_ESTRATEGIA" ("CODIGO","NOME","DESCRICAO","PARAMETROS","ORDEM","ATIVO") VALUES
 ('LOCALIDADE_ALTA_ADESAO','Localidades de alta adesão com bolsões sem provedor',
  'Ranqueia as localidades pela proporção de postes COM provedor (adesão alta = mercado maduro) e, dentro delas, seleciona os que ainda estão SEM provedor - candidatos a cadastro pendente.',
  'min_adesao (padrão 0.4)',30,'S');
INSERT INTO "CLB349328"."PORTAL_COMPARTILHAMENTO_CARTEIRA_ESTRATEGIA" ("CODIGO","NOME","DESCRICAO","PARAMETROS","ORDEM","ATIVO") VALUES
 ('DENSIDADE_SEM_PROVEDOR','Concentração de postes sem provedor perto de área atendida',
  'Encontra aglomerados de postes SEM provedor que ficam próximos (célula vizinha) de postes COM provedor. Aponta mercado potencial contíguo a rede existente.',
  'celula_m (padrão 200)',40,'S');
INSERT INTO "CLB349328"."PORTAL_COMPARTILHAMENTO_CARTEIRA_ESTRATEGIA" ("CODIGO","NOME","DESCRICAO","PARAMETROS","ORDEM","ATIVO") VALUES
 ('AMOSTRAGEM_LOCALIDADE','Amostragem simples por município/localidade',
  'Sem priorização: pega N postes SEM provedor por dia nos municípios/localidades escolhidos, na ordem do cadastro. Útil para varredura ampla.',
  'nenhum',50,'S');
INSERT INTO "CLB349328"."PORTAL_COMPARTILHAMENTO_CARTEIRA_ESTRATEGIA" ("CODIGO","NOME","DESCRICAO","PARAMETROS","ORDEM","ATIVO") VALUES
 ('TODOS_SEM_PROVEDOR','Todos os postes sem provedor da área',
  'Sem amostragem: inclui todos os postes SEM provedor dos municípios/localidades escolhidos, limitado pela capacidade das equipes no período.',
  'nenhum',60,'S');


-- ---------------------------------------------------------------------
-- 4) CARTEIRA (cabeçalho)
-- ---------------------------------------------------------------------
CREATE COLUMN TABLE "CLB349328"."PORTAL_COMPARTILHAMENTO_CARTEIRA"
(
    "ID_CARTEIRA"      INTEGER CS_INT GENERATED BY DEFAULT AS IDENTITY,
    "TITULO"           NVARCHAR(200),
    "FREQUENCIA"       NVARCHAR(10)  DEFAULT 'SEMANAL',  -- DIARIA | SEMANAL | MENSAL
    "DATA_INICIO"      DATE NOT NULL,
    "DATA_FIM"         DATE NOT NULL,
    "MODO"             NVARCHAR(12)  DEFAULT 'AUTOMATICA', -- MANUAL | AUTOMATICA
    "ESTRATEGIA"       NVARCHAR(40),                    -- -> CARTEIRA_ESTRATEGIA.CODIGO (só no modo AUTOMATICA)
    "ID_EPS"           INTEGER,
    "QTD_POSTES_DIA"   INTEGER DEFAULT 12,
    "QTD_OS"           INTEGER DEFAULT 0,
    "QTD_EQUIPES"      INTEGER DEFAULT 0,
    "STATUS"           NVARCHAR(15) DEFAULT 'RASCUNHO', -- RASCUNHO | PUBLICADA | CONCLUIDA | CANCELADA
    "PARAMETROS_JSON"  NVARCHAR(4000),                  -- eco dos parâmetros usados na geração
    "CREATED_AT"       LONGDATE CS_LONGDATE,
    "CREATED_BY"       NVARCHAR(100),
    "UPDATED_AT"       LONGDATE CS_LONGDATE,
    PRIMARY KEY ("ID_CARTEIRA")
)
UNLOAD PRIORITY 5 AUTO MERGE;

CREATE INDEX "IX_CARTEIRA_STATUS" ON "CLB349328"."PORTAL_COMPARTILHAMENTO_CARTEIRA" ("STATUS");
CREATE INDEX "IX_CARTEIRA_INICIO" ON "CLB349328"."PORTAL_COMPARTILHAMENTO_CARTEIRA" ("DATA_INICIO");


-- ---------------------------------------------------------------------
-- 5) MUNICÍPIOS/LOCALIDADES no escopo da carteira
-- ---------------------------------------------------------------------
CREATE COLUMN TABLE "CLB349328"."PORTAL_COMPARTILHAMENTO_CARTEIRA_ESCOPO"
(
    "ID"               INTEGER CS_INT GENERATED BY DEFAULT AS IDENTITY,
    "ID_CARTEIRA"      INTEGER NOT NULL,
    "MUNICIPIO"        NVARCHAR(120),
    "NU_LOCALIDADE_ID" BIGINT,                          -- nulo = município inteiro
    PRIMARY KEY ("ID")
)
UNLOAD PRIORITY 5 AUTO MERGE;

CREATE INDEX "IX_CARTESCOPO_CARTEIRA" ON "CLB349328"."PORTAL_COMPARTILHAMENTO_CARTEIRA_ESCOPO" ("ID_CARTEIRA");


-- ---------------------------------------------------------------------
-- 6) ORDENS DE SERVIÇO da carteira (1 linha por poste/dia/equipe)
-- ---------------------------------------------------------------------
CREATE COLUMN TABLE "CLB349328"."PORTAL_COMPARTILHAMENTO_CARTEIRA_OS"
(
    "ID_CARTEIRA_OS"  INTEGER CS_INT GENERATED BY DEFAULT AS IDENTITY,
    "ID_CARTEIRA"     INTEGER NOT NULL,
    "SEQ"             INTEGER,                          -- ordem global na carteira

    "NU_PG_ID"        BIGINT,                           -- -> BASE_POSTE.NU_PG_ID
    "DE_BARRAMENTO"   NVARCHAR(50),
    "MUNICIPIO"       NVARCHAR(120),
    "LOCALIDADE"      NVARCHAR(120),
    "LATITUDE"        DECIMAL(18,10),
    "LONGITUDE"       DECIMAL(18,10),
    "TEM_PROVEDOR"    NVARCHAR(1) DEFAULT 'N',

    "ID_EQUIPE"       INTEGER,
    "NOME_EQUIPE"     NVARCHAR(80),
    "EPS"             NVARCHAR(150),

    "DATA_PREVISTA"   DATE,
    "DIA_INDICE"      INTEGER,                          -- 1..N dias úteis da carteira
    "ORDEM_NO_DIA"    INTEGER,                          -- sequência da rota naquele dia

    "ESTRATEGIA"      NVARCHAR(40),
    "SCORE"           DECIMAL(9,4),                     -- pontuação da estratégia (evidência)
    "MOTIVO"          NVARCHAR(300),                    -- porque este poste entrou

    "STATUS"          NVARCHAR(15) DEFAULT 'PLANEJADA', -- PLANEJADA | EM_ROTA | EXECUTADA | CANCELADA
    "LINK_GMAPS"      NVARCHAR(300),
    "LINK_WAZE"       NVARCHAR(300),
    "EXECUTADO_EM"    LONGDATE CS_LONGDATE,
    "OBSERVACAO"      NVARCHAR(1000),
    "CREATED_AT"      LONGDATE CS_LONGDATE,
    PRIMARY KEY ("ID_CARTEIRA_OS")
)
UNLOAD PRIORITY 5 AUTO MERGE;

CREATE INDEX "IX_CARTOS_CARTEIRA"  ON "CLB349328"."PORTAL_COMPARTILHAMENTO_CARTEIRA_OS" ("ID_CARTEIRA");
CREATE INDEX "IX_CARTOS_EQUIPE"    ON "CLB349328"."PORTAL_COMPARTILHAMENTO_CARTEIRA_OS" ("ID_EQUIPE");
CREATE INDEX "IX_CARTOS_DATA"      ON "CLB349328"."PORTAL_COMPARTILHAMENTO_CARTEIRA_OS" ("DATA_PREVISTA");


-- ---------------------------------------------------------------------
--  Domínios (validados no backend, não por constraint):
--   CARTEIRA.FREQUENCIA : DIARIA | SEMANAL | MENSAL
--   CARTEIRA.MODO       : MANUAL | AUTOMATICA
--   CARTEIRA.STATUS     : RASCUNHO | PUBLICADA | CONCLUIDA | CANCELADA
--   CARTEIRA_OS.STATUS  : PLANEJADA | EM_ROTA | EXECUTADA | CANCELADA
--   EPS.TIPO_SERVICO / EQUIPE_CAMPO.TIPO : FISCALIZACAO | REMOCAO | AMBOS
-- ---------------------------------------------------------------------
