-- =====================================================================
--  Projetos de Compartilhamento de Infraestrutura
--  DDL para SAP HANA (schema de trabalho: ajuste "CLB349328" se for outro)
--
--  Segue o mesmo padrão do resto do portal:
--    - CREATE COLUMN TABLE ... UNLOAD PRIORITY 5 AUTO MERGE
--    - PK INTEGER CS_INT GENERATED BY DEFAULT AS IDENTITY
--    - texto NVARCHAR(n); data/hora LONGDATE CS_LONGDATE
--    - flags S/N em NVARCHAR(1) DEFAULT 'N'
--    - coordenadas em DECIMAL(18,10) (igual a POSTE.X / .Y e ACAO_POSTE.MIN_X)
--    - SEM foreign keys / check constraints: os domínios são validados no
--      backend, como já acontece com PROVEDOR / PROCESSO / SOLICITACAO_ACAO.
--
--  Vínculo com a jornada do provedor
--  ---------------------------------
--  O projeto chega por e-mail ANTES de existir (ou sem que se saiba) um
--  provedor/processo cadastrado. Por isso o elo é feito em duas camadas:
--
--    1. CHAVE_CONEXAO  -> chave natural, sempre preenchida: o CNPJ do
--       provedor só com dígitos (14 caracteres). É o que amarra o projeto
--       à identidade do provedor mesmo antes de haver FK resolvida.
--    2. ID_PROVEDOR / ID_PROCESSO -> FKs lógicas, preenchidas quando o
--       backend consegue casar a CHAVE_CONEXAO com
--       PORTAL_COMPARTILHAMENTO_PROVEDOR (por CNPJ) e, opcionalmente, com
--       um PORTAL_COMPARTILHAMENTO_PROCESSO daquele provedor.
--
--  Fluxo de análise (STATUS_PROJETO, validado em código):
--    RECEBIDO -> EM_ANALISE -> PENDENTE_DOC -> ANALISE_TECNICA
--             -> PARECER_EMITIDO -> VINCULADO -> CONCLUIDO
--             -> (a qualquer momento) DEVOLVIDO | CANCELADO
-- =====================================================================


-- ---------------------------------------------------------------------
-- 1) PROJETO  (cabeçalho — 1 linha por projeto recebido)
-- ---------------------------------------------------------------------
CREATE COLUMN TABLE "CLB349328"."PORTAL_COMPARTILHAMENTO_PROJETO"
(
    "ID_PROJETO"            INTEGER CS_INT GENERATED BY DEFAULT AS IDENTITY,
    "NUMERO_PROJETO"        NVARCHAR(40)  NOT NULL,       -- ex.: PRJ-2026-000123
    "TITULO"                NVARCHAR(200),

    -- Vínculo com a jornada do provedor
    "CHAVE_CONEXAO"         NVARCHAR(14)  NOT NULL,       -- CNPJ só dígitos
    "ID_PROVEDOR"           INTEGER,                      -- resolvido -> PROVEDOR.ID_PROVEDOR
    "ID_PROCESSO"           INTEGER,                      -- opcional -> PROCESSO.ID_PROCESSO
    "NUMERO_PROTOCOLO"      NVARCHAR(30),                 -- cópia do PROCESSO, p/ exibição

    -- Identificação do provedor (denormalizado — vem no e-mail/planilha)
    "CNPJ"                  NVARCHAR(20)  NOT NULL,       -- formatado
    "RAZAO_SOCIAL"          NVARCHAR(200) NOT NULL,
    "NOME_FANTASIA"         NVARCHAR(200),

    -- Localização principal do projeto
    "MUNICIPIO"             NVARCHAR(120),
    "UF"                    NVARCHAR(2),
    "REGIONAL"              NVARCHAR(60),

    -- Volumetria
    "QTD_POSTES_INFORMADA"  INTEGER       DEFAULT 0,      -- o que o provedor declarou
    "QTD_POSTES_RECEBIDA"   INTEGER       DEFAULT 0,      -- o que veio na planilha de postes
    "QTD_POSTES_VALIDADA"   INTEGER       DEFAULT 0,      -- aprovados na análise técnica

    -- Situação da análise
    "STATUS_PROJETO"        NVARCHAR(20)  DEFAULT 'RECEBIDO',
    "PRIORIDADE"            NVARCHAR(10)  DEFAULT 'MEDIA',
    "RESPONSAVEL_ANALISE"   NVARCHAR(100),
    "PRAZO_ANALISE"         DATE,
    "DATA_CONCLUSAO"        LONGDATE CS_LONGDATE,

    -- Origem / submissão
    "CANAL_ORIGEM"          NVARCHAR(20)  DEFAULT 'EMAIL', -- EMAIL | UPLOAD | API
    "SUBMETIDO_POR"         NVARCHAR(100),                 -- usuário do portal que registrou
    "EMAIL_REMETENTE"       NVARCHAR(200),                 -- de quem veio o e-mail
    "DATA_RECEBIMENTO"      LONGDATE CS_LONGDATE,

    -- Conferência documental (resumo rápido; detalhe em PROJETO_DOCUMENTO)
    "DOCS_OBRIGATORIOS"     INTEGER       DEFAULT 0,
    "DOCS_RECEBIDOS"        INTEGER       DEFAULT 0,
    "DOCS_VALIDADOS"        INTEGER       DEFAULT 0,
    "DOCUMENTACAO_OK"       NVARCHAR(1)   DEFAULT 'N',

    "OBSERVACOES"           NVARCHAR(4000),

    -- Auditoria
    "CREATED_AT"            LONGDATE CS_LONGDATE,
    "CREATED_BY"            NVARCHAR(100),
    "UPDATED_AT"            LONGDATE CS_LONGDATE,
    "UPDATED_BY"            NVARCHAR(100),
    "ATIVO"                 NVARCHAR(1)   DEFAULT 'S',

    PRIMARY KEY ("ID_PROJETO")
)
UNLOAD PRIORITY 5 AUTO MERGE;

CREATE UNIQUE INDEX "IX_PROJETO_NUMERO"   ON "CLB349328"."PORTAL_COMPARTILHAMENTO_PROJETO" ("NUMERO_PROJETO");
CREATE INDEX        "IX_PROJETO_CHAVE"    ON "CLB349328"."PORTAL_COMPARTILHAMENTO_PROJETO" ("CHAVE_CONEXAO");
CREATE INDEX        "IX_PROJETO_PROVEDOR" ON "CLB349328"."PORTAL_COMPARTILHAMENTO_PROJETO" ("ID_PROVEDOR");
CREATE INDEX        "IX_PROJETO_PROCESSO" ON "CLB349328"."PORTAL_COMPARTILHAMENTO_PROJETO" ("ID_PROCESSO");
CREATE INDEX        "IX_PROJETO_STATUS"   ON "CLB349328"."PORTAL_COMPARTILHAMENTO_PROJETO" ("STATUS_PROJETO");


-- ---------------------------------------------------------------------
-- 2) PROJETO_POSTE  (1:N — os postes do projeto, com lat/long)
-- ---------------------------------------------------------------------
CREATE COLUMN TABLE "CLB349328"."PORTAL_COMPARTILHAMENTO_PROJETO_POSTE"
(
    "ID_PROJETO_POSTE"     INTEGER CS_INT GENERATED BY DEFAULT AS IDENTITY,
    "ID_PROJETO"           INTEGER       NOT NULL,

    -- Identificador do poste como veio na planilha do provedor
    "IDENTIFICADOR_POSTE"  NVARCHAR(60),                  -- código do provedor
    "BARRAMENTO"           NVARCHAR(50),                  -- casado com PORTAL_COMPARTILHAMENTO_POSTE.BARRAMENTO
    "ID_POSTE_PORTAL"      INTEGER,                       -- id do poste no cadastro oficial, se casou

    -- Geolocalização (mesma precisão de POSTE.X / .Y)
    "LATITUDE"             DECIMAL(18,10),                -- = Y
    "LONGITUDE"            DECIMAL(18,10),                -- = X

    -- Endereço textual
    "MUNICIPIO"            NVARCHAR(120),
    "UF"                   NVARCHAR(2),
    "LOGRADOURO"           NVARCHAR(200),
    "BAIRRO"               NVARCHAR(120),
    "CEP"                  NVARCHAR(10),

    -- Ocupação pretendida
    "TIPO_OCUPACAO"        NVARCHAR(40),                  -- FIBRA | COAXIAL | ...
    "QTD_PONTOS_FIXACAO"   INTEGER       DEFAULT 1,

    -- Resultado da análise técnica deste poste
    "STATUS_ANALISE"       NVARCHAR(20)  DEFAULT 'PENDENTE', -- PENDENTE | APROVADO | REPROVADO | REVISAR
    "MOTIVO_REPROVACAO"    NVARCHAR(300),
    "GEO_VALIDADA"         NVARCHAR(1)   DEFAULT 'N',      -- lat/long dentro da área de concessão
    "POSTE_LOCALIZADO"     NVARCHAR(1)   DEFAULT 'N',      -- casou com um poste do cadastro
    "OBSERVACAO"           NVARCHAR(1000),

    "CREATED_AT"           LONGDATE CS_LONGDATE,
    "UPDATED_AT"           LONGDATE CS_LONGDATE,

    PRIMARY KEY ("ID_PROJETO_POSTE")
)
UNLOAD PRIORITY 5 AUTO MERGE;

CREATE INDEX "IX_PROJPOSTE_PROJETO"    ON "CLB349328"."PORTAL_COMPARTILHAMENTO_PROJETO_POSTE" ("ID_PROJETO");
CREATE INDEX "IX_PROJPOSTE_BARRAMENTO" ON "CLB349328"."PORTAL_COMPARTILHAMENTO_PROJETO_POSTE" ("BARRAMENTO");
CREATE INDEX "IX_PROJPOSTE_STATUS"     ON "CLB349328"."PORTAL_COMPARTILHAMENTO_PROJETO_POSTE" ("STATUS_ANALISE");


-- ---------------------------------------------------------------------
-- 3) PROJETO_TIPO_DOCUMENTO  (catálogo — quais documentos são exigidos)
--    Parametrização, no estilo de PORTAL_COMPARTILHAMENTO_ETAPA.
-- ---------------------------------------------------------------------
CREATE COLUMN TABLE "CLB349328"."PORTAL_COMPARTILHAMENTO_PROJETO_TIPO_DOCUMENTO"
(
    "ID_TIPO_DOCUMENTO"    INTEGER CS_INT GENERATED BY DEFAULT AS IDENTITY,
    "CODIGO"               NVARCHAR(40)  NOT NULL,        -- ex.: PLANILHA_POSTES
    "NOME"                 NVARCHAR(150) NOT NULL,
    "DESCRICAO"            NVARCHAR(500),
    "OBRIGATORIO"          NVARCHAR(1)   DEFAULT 'S',
    "EXTENSOES_ACEITAS"    NVARCHAR(120),                 -- ex.: pdf,xlsx,csv,kml
    "ORDEM"                INTEGER       DEFAULT 0,
    "ATIVO"                NVARCHAR(1)   DEFAULT 'S',
    "CREATED_AT"           LONGDATE CS_LONGDATE,
    "UPDATED_AT"           LONGDATE CS_LONGDATE,

    PRIMARY KEY ("ID_TIPO_DOCUMENTO")
)
UNLOAD PRIORITY 5 AUTO MERGE;

CREATE UNIQUE INDEX "IX_PROJTIPODOC_CODIGO" ON "CLB349328"."PORTAL_COMPARTILHAMENTO_PROJETO_TIPO_DOCUMENTO" ("CODIGO");

-- Seed do catálogo de documentos (ajuste conforme a norma vigente)
INSERT INTO "CLB349328"."PORTAL_COMPARTILHAMENTO_PROJETO_TIPO_DOCUMENTO"
    ("CODIGO","NOME","DESCRICAO","OBRIGATORIO","EXTENSOES_ACEITAS","ORDEM","ATIVO","CREATED_AT")
VALUES ('OFICIO_SOLICITACAO','Ofício de solicitação de compartilhamento','Carta formal do provedor solicitando o uso da infraestrutura.','S','pdf',10,'S',CURRENT_UTCTIMESTAMP);
INSERT INTO "CLB349328"."PORTAL_COMPARTILHAMENTO_PROJETO_TIPO_DOCUMENTO"
    ("CODIGO","NOME","DESCRICAO","OBRIGATORIO","EXTENSOES_ACEITAS","ORDEM","ATIVO","CREATED_AT")
VALUES ('PLANILHA_POSTES','Planilha de postes','Relação dos postes com identificador, latitude e longitude.','S','xlsx,csv',20,'S',CURRENT_UTCTIMESTAMP);
INSERT INTO "CLB349328"."PORTAL_COMPARTILHAMENTO_PROJETO_TIPO_DOCUMENTO"
    ("CODIGO","NOME","DESCRICAO","OBRIGATORIO","EXTENSOES_ACEITAS","ORDEM","ATIVO","CREATED_AT")
VALUES ('PROJETO_TECNICO','Projeto técnico / memorial descritivo','Memorial descritivo da rede a ser instalada.','S','pdf',30,'S',CURRENT_UTCTIMESTAMP);
INSERT INTO "CLB349328"."PORTAL_COMPARTILHAMENTO_PROJETO_TIPO_DOCUMENTO"
    ("CODIGO","NOME","DESCRICAO","OBRIGATORIO","EXTENSOES_ACEITAS","ORDEM","ATIVO","CREATED_AT")
VALUES ('ART_TRT','ART / TRT do responsável técnico','Anotação/Termo de Responsabilidade Técnica.','S','pdf',40,'S',CURRENT_UTCTIMESTAMP);
INSERT INTO "CLB349328"."PORTAL_COMPARTILHAMENTO_PROJETO_TIPO_DOCUMENTO"
    ("CODIGO","NOME","DESCRICAO","OBRIGATORIO","EXTENSOES_ACEITAS","ORDEM","ATIVO","CREATED_AT")
VALUES ('LICENCA_ANATEL','Licença / outorga ANATEL','Comprovante de autorização junto à ANATEL (SCM/SLP).','S','pdf',50,'S',CURRENT_UTCTIMESTAMP);
INSERT INTO "CLB349328"."PORTAL_COMPARTILHAMENTO_PROJETO_TIPO_DOCUMENTO"
    ("CODIGO","NOME","DESCRICAO","OBRIGATORIO","EXTENSOES_ACEITAS","ORDEM","ATIVO","CREATED_AT")
VALUES ('CONTRATO_SOCIAL','Contrato social / CNPJ','Cartão CNPJ e contrato social atualizado.','S','pdf',60,'S',CURRENT_UTCTIMESTAMP);
INSERT INTO "CLB349328"."PORTAL_COMPARTILHAMENTO_PROJETO_TIPO_DOCUMENTO"
    ("CODIGO","NOME","DESCRICAO","OBRIGATORIO","EXTENSOES_ACEITAS","ORDEM","ATIVO","CREATED_AT")
VALUES ('KML_TRACADO','Arquivo KML/KMZ do traçado','Traçado georreferenciado da rota (opcional, acelera a análise).','N','kml,kmz',70,'S',CURRENT_UTCTIMESTAMP);


-- ---------------------------------------------------------------------
-- 4) PROJETO_DOCUMENTO  (1:N — os arquivos de cada projeto)
-- ---------------------------------------------------------------------
CREATE COLUMN TABLE "CLB349328"."PORTAL_COMPARTILHAMENTO_PROJETO_DOCUMENTO"
(
    "ID_PROJETO_DOCUMENTO" INTEGER CS_INT GENERATED BY DEFAULT AS IDENTITY,
    "ID_PROJETO"           INTEGER       NOT NULL,
    "ID_SUBMISSAO"         INTEGER,                       -- e-mail que trouxe o arquivo
    "CODIGO_TIPO"          NVARCHAR(40),                  -- = PROJETO_TIPO_DOCUMENTO.CODIGO
    "TIPO_DOCUMENTO"       NVARCHAR(150),                 -- nome amigável (cópia)
    "OBRIGATORIO"          NVARCHAR(1)   DEFAULT 'N',

    "NOME_ARQUIVO"         NVARCHAR(255),
    "TIPO_ARQUIVO"         NVARCHAR(120),                 -- mime/type
    "CAMINHO_ARQUIVO"      NVARCHAR(1000),                -- link SharePoint / storage
    "TAMANHO_BYTES"        BIGINT,
    "HASH_ARQUIVO"         NVARCHAR(64),                  -- sha-256, p/ deduplicar anexos

    "STATUS_DOCUMENTO"     NVARCHAR(20)  DEFAULT 'PENDENTE', -- PENDENTE | RECEBIDO | VALIDADO | REJEITADO
    "MOTIVO_REJEICAO"      NVARCHAR(500),

    "RECEBIDO_VIA"         NVARCHAR(20)  DEFAULT 'EMAIL',
    "EMAIL_REMETENTE"      NVARCHAR(200),
    "DATA_RECEBIMENTO"     LONGDATE CS_LONGDATE,
    "VALIDADO_POR"         NVARCHAR(100),
    "DATA_VALIDACAO"       LONGDATE CS_LONGDATE,

    "OBSERVACAO"           NVARCHAR(1000),
    "CREATED_AT"           LONGDATE CS_LONGDATE,
    "ATIVO"                NVARCHAR(1)   DEFAULT 'S',

    PRIMARY KEY ("ID_PROJETO_DOCUMENTO")
)
UNLOAD PRIORITY 5 AUTO MERGE;

CREATE INDEX "IX_PROJDOC_PROJETO"   ON "CLB349328"."PORTAL_COMPARTILHAMENTO_PROJETO_DOCUMENTO" ("ID_PROJETO");
CREATE INDEX "IX_PROJDOC_TIPO"      ON "CLB349328"."PORTAL_COMPARTILHAMENTO_PROJETO_DOCUMENTO" ("CODIGO_TIPO");
CREATE INDEX "IX_PROJDOC_STATUS"    ON "CLB349328"."PORTAL_COMPARTILHAMENTO_PROJETO_DOCUMENTO" ("STATUS_DOCUMENTO");
CREATE INDEX "IX_PROJDOC_SUBMISSAO" ON "CLB349328"."PORTAL_COMPARTILHAMENTO_PROJETO_DOCUMENTO" ("ID_SUBMISSAO");


-- ---------------------------------------------------------------------
-- 5) PROJETO_SUBMISSAO  (1:N — cada e-mail/entrega que alimentou o projeto)
--    Guarda o rastro do e-mail e quem, no portal, fez a triagem.
-- ---------------------------------------------------------------------
CREATE COLUMN TABLE "CLB349328"."PORTAL_COMPARTILHAMENTO_PROJETO_SUBMISSAO"
(
    "ID_SUBMISSAO"         INTEGER CS_INT GENERATED BY DEFAULT AS IDENTITY,
    "ID_PROJETO"           INTEGER,                       -- nulo enquanto não triado
    "CHAVE_CONEXAO"        NVARCHAR(14),                  -- CNPJ dos dígitos, extraído do e-mail

    -- Dados do e-mail
    "MESSAGE_ID"           NVARCHAR(255),                 -- Message-ID do e-mail (dedupe)
    "EMAIL_REMETENTE"      NVARCHAR(200),
    "EMAIL_PARA"           NVARCHAR(200),                 -- caixa institucional que recebeu
    "ASSUNTO"              NVARCHAR(500),
    "CORPO_RESUMO"         NVARCHAR(4000),
    "DATA_EMAIL"           LONGDATE CS_LONGDATE,
    "QTD_ANEXOS"           INTEGER       DEFAULT 0,

    -- Triagem no portal
    "STATUS_SUBMISSAO"     NVARCHAR(20)  DEFAULT 'NOVO',  -- NOVO | TRIADA | VINCULADA | DESCARTADA
    "MOTIVO_DESCARTE"      NVARCHAR(500),
    "SUBMETIDO_POR"        NVARCHAR(100),                 -- usuário do portal que submeteu/triou
    "DATA_SUBMISSAO"       LONGDATE CS_LONGDATE,
    "PROCESSADO_EM"        LONGDATE CS_LONGDATE,

    "CREATED_AT"           LONGDATE CS_LONGDATE,

    PRIMARY KEY ("ID_SUBMISSAO")
)
UNLOAD PRIORITY 5 AUTO MERGE;

CREATE UNIQUE INDEX "IX_PROJSUB_MSGID"  ON "CLB349328"."PORTAL_COMPARTILHAMENTO_PROJETO_SUBMISSAO" ("MESSAGE_ID");
CREATE INDEX        "IX_PROJSUB_PROJETO" ON "CLB349328"."PORTAL_COMPARTILHAMENTO_PROJETO_SUBMISSAO" ("ID_PROJETO");
CREATE INDEX        "IX_PROJSUB_CHAVE"   ON "CLB349328"."PORTAL_COMPARTILHAMENTO_PROJETO_SUBMISSAO" ("CHAVE_CONEXAO");
CREATE INDEX        "IX_PROJSUB_STATUS"  ON "CLB349328"."PORTAL_COMPARTILHAMENTO_PROJETO_SUBMISSAO" ("STATUS_SUBMISSAO");


-- ---------------------------------------------------------------------
-- 6) PROJETO_ANALISE  (1:N — parecer/checklist da análise; permite reanálise)
-- ---------------------------------------------------------------------
CREATE COLUMN TABLE "CLB349328"."PORTAL_COMPARTILHAMENTO_PROJETO_ANALISE"
(
    "ID_ANALISE"          INTEGER CS_INT GENERATED BY DEFAULT AS IDENTITY,
    "ID_PROJETO"          INTEGER       NOT NULL,

    -- Checklist (S/N/NA)
    "DOC_CONFERIDA"       NVARCHAR(1)   DEFAULT 'N',
    "CNPJ_REGULAR"        NVARCHAR(1)   DEFAULT 'N',
    "LICENCA_ANATEL_OK"   NVARCHAR(1)   DEFAULT 'N',
    "POSTES_LOCALIZADOS"  NVARCHAR(1)   DEFAULT 'N',
    "GEO_DENTRO_CONCESSAO" NVARCHAR(1)  DEFAULT 'N',
    "CAPACIDADE_SUFICIENTE" NVARCHAR(1) DEFAULT 'N',      -- postes têm ponto de fixação livre

    "RESULTADO"           NVARCHAR(20),                   -- APROVADO | APROVADO_PARCIAL | REPROVADO | PENDENCIA
    "PARECER"             NVARCHAR(4000),
    "QTD_POSTES_APROVADOS" INTEGER      DEFAULT 0,
    "QTD_POSTES_REPROVADOS" INTEGER     DEFAULT 0,

    "USUARIO_ANALISE"     NVARCHAR(100),
    "DATA_ANALISE"        LONGDATE CS_LONGDATE,
    "CREATED_AT"          LONGDATE CS_LONGDATE,

    PRIMARY KEY ("ID_ANALISE")
)
UNLOAD PRIORITY 5 AUTO MERGE;

CREATE INDEX "IX_PROJANALISE_PROJETO" ON "CLB349328"."PORTAL_COMPARTILHAMENTO_PROJETO_ANALISE" ("ID_PROJETO");


-- ---------------------------------------------------------------------
-- 7) PROJETO_HISTORICO  (trilha de auditoria — 1 linha por evento)
-- ---------------------------------------------------------------------
CREATE COLUMN TABLE "CLB349328"."PORTAL_COMPARTILHAMENTO_PROJETO_HISTORICO"
(
    "ID_HISTORICO"        INTEGER CS_INT GENERATED BY DEFAULT AS IDENTITY,
    "ID_PROJETO"          INTEGER       NOT NULL,
    "TIPO_EVENTO"         NVARCHAR(30),                   -- RECEBIMENTO | STATUS | DOCUMENTO | ANALISE | VINCULO | ATRIBUICAO
    "STATUS_ANTERIOR"     NVARCHAR(20),
    "STATUS_NOVO"         NVARCHAR(20),
    "DESCRICAO"           NVARCHAR(1000),
    "USUARIO"             NVARCHAR(100),
    "DATA_EVENTO"         LONGDATE CS_LONGDATE,

    PRIMARY KEY ("ID_HISTORICO")
)
UNLOAD PRIORITY 5 AUTO MERGE;

CREATE INDEX "IX_PROJHIST_PROJETO" ON "CLB349328"."PORTAL_COMPARTILHAMENTO_PROJETO_HISTORICO" ("ID_PROJETO");


-- =====================================================================
--  VIEW de apoio: projeto + jornada do provedor resolvida pela CHAVE_CONEXAO
--  (útil pra tela "Vínculo" e pra relatórios; não substitui os FKs gravados)
-- =====================================================================
CREATE VIEW "CLB349328"."V_PORTAL_COMPARTILHAMENTO_PROJETO_JORNADA" AS
SELECT
    PJ."ID_PROJETO",
    PJ."NUMERO_PROJETO",
    PJ."CHAVE_CONEXAO",
    PJ."STATUS_PROJETO",
    PJ."CNPJ",
    PJ."RAZAO_SOCIAL",
    PJ."NOME_FANTASIA",
    PR."ID_PROVEDOR",
    PR."STATUS_CADASTRO",
    PC."ID_PROCESSO",
    PC."NUMERO_PROTOCOLO",
    PC."STATUS_ATUAL"           AS "STATUS_PROCESSO",
    PC."ETAPA_ATUAL"
FROM "CLB349328"."PORTAL_COMPARTILHAMENTO_PROJETO" PJ
LEFT JOIN "CLB349328"."PORTAL_COMPARTILHAMENTO_PROVEDOR" PR
    ON REPLACE(REPLACE(REPLACE(PR."CNPJ",'.',''),'/',''),'-','') = PJ."CHAVE_CONEXAO"
LEFT JOIN "CLB349328"."PORTAL_COMPARTILHAMENTO_PROCESSO" PC
    ON PC."ID_PROVEDOR" = PR."ID_PROVEDOR"
   AND (PJ."ID_PROCESSO" IS NULL OR PC."ID_PROCESSO" = PJ."ID_PROCESSO")
WHERE PJ."ATIVO" = 'S';


-- =====================================================================
--  Domínios de valores (validados no backend, não por constraint):
--
--  PROJETO.STATUS_PROJETO :
--    RECEBIDO | EM_ANALISE | PENDENTE_DOC | ANALISE_TECNICA |
--    PARECER_EMITIDO | VINCULADO | CONCLUIDO | DEVOLVIDO | CANCELADO
--  PROJETO.PRIORIDADE : BAIXA | MEDIA | ALTA | URGENTE
--  PROJETO.CANAL_ORIGEM : EMAIL | UPLOAD | API
--
--  PROJETO_POSTE.STATUS_ANALISE : PENDENTE | APROVADO | REPROVADO | REVISAR
--  PROJETO_POSTE.TIPO_OCUPACAO  : FIBRA | COAXIAL | ENERGIA | OUTRO
--
--  PROJETO_DOCUMENTO.STATUS_DOCUMENTO : PENDENTE | RECEBIDO | VALIDADO | REJEITADO
--  PROJETO_DOCUMENTO.RECEBIDO_VIA     : EMAIL | UPLOAD | SHAREPOINT
--
--  PROJETO_SUBMISSAO.STATUS_SUBMISSAO : NOVO | TRIADA | VINCULADA | DESCARTADA
--
--  PROJETO_ANALISE.RESULTADO : APROVADO | APROVADO_PARCIAL | REPROVADO | PENDENCIA
--  PROJETO_HISTORICO.TIPO_EVENTO :
--    RECEBIMENTO | STATUS | DOCUMENTO | ANALISE | VINCULO | ATRIBUICAO
-- =====================================================================
