-- =====================================================================
--  Área de atuação das EPS (tabela de suporte)
--
--  Relaciona a EPS (Empresa Prestadora de Serviço) com os municípios
--  onde ela atende. É a fonte de "qual EPS atende cada município" no
--  gerador de Carteira de Serviço: o usuário escolhe a EPS e os
--  municípios disponíveis se restringem à área dela.
--
--  Uma linha por (EPS, MUNICIPIO). Um mesmo município pode ter mais de
--  uma EPS => mais de uma linha.
--
--  EPS cadastradas (PORTAL_COMPARTILHAMENTO_EPS): CADIC, ELEKTRA, ORC,
--  DINAMO.
--  Schema de trabalho: ajuste "CLB349328" se o seu for outro.
-- =====================================================================

CREATE COLUMN TABLE "CLB349328"."PORTAL_COMPARTILHAMENTO_EPS_ATUACAO"
(
    "ID"          INTEGER CS_INT GENERATED BY DEFAULT AS IDENTITY,
    "ID_EPS"      INTEGER NOT NULL,               -- -> PORTAL_COMPARTILHAMENTO_EPS.ID_EPS
    "MUNICIPIO"   NVARCHAR(120) NOT NULL,
    "ATIVO"       NVARCHAR(1) DEFAULT 'S',
    "CREATED_AT"  LONGDATE CS_LONGDATE,
    "CREATED_BY"  NVARCHAR(100),
    "UPDATED_AT"  LONGDATE CS_LONGDATE,
    PRIMARY KEY ("ID")
)
UNLOAD PRIORITY 5 AUTO MERGE;

CREATE UNIQUE INDEX "IX_EPSATUACAO_EPS_MUN"
    ON "CLB349328"."PORTAL_COMPARTILHAMENTO_EPS_ATUACAO" ("ID_EPS", "MUNICIPIO");
CREATE INDEX "IX_EPSATUACAO_MUNICIPIO"
    ON "CLB349328"."PORTAL_COMPARTILHAMENTO_EPS_ATUACAO" ("MUNICIPIO");


-- Consulta típica: municípios atendidos por uma EPS.
--   SELECT A.MUNICIPIO
--   FROM "CLB349328"."PORTAL_COMPARTILHAMENTO_EPS_ATUACAO" A
--   JOIN "CLB349328"."PORTAL_COMPARTILHAMENTO_EPS" E ON E.ID_EPS = A.ID_EPS
--   WHERE A.ATIVO = 'S' AND E.ATIVO = 'S' AND A.ID_EPS = ?;
