-- =====================================================================
-- Resultado Financeiro mensal (Faturamento, Custos, Receita Liquida)
-- Acompanhamento Meta x Realizado x REV (revisao/projecao), mensal e YTD.
-- Consumido por app/(app)/resultados/resultadofinanceiro/page.tsx
-- e mock-api-dev/routes-resultado-financeiro.js.
--
-- Modelagem: uma linha por (ANO, MES, INDICADOR). O acumulado YTD e o
-- desvio (REALIZADO - META) NUNCA sao gravados - sao sempre recalculados
-- no backend a partir de META / REALIZADO / REV, pra nunca dessincronizar.
--
-- INDICADOR e um dominio fixo controlado pela aplicacao (sem CHECK no
-- banco, seguindo o padrao das demais tabelas do portal):
--   FATURAMENTO       - receita bruta faturada no mes
--   CUSTOS            - custos e despesas do mes
--   RECEITA_LIQUIDA   - receita liquida (linha orcada propria; pode
--                       divergir de FATURAMENTO - CUSTOS por impostos,
--                       deducoes e ajustes)
-- Outros indicadores financeiros entram depois, so acrescentando o
-- codigo no dominio da aplicacao - o schema nao muda.
-- =====================================================================

CREATE COLUMN TABLE "CLB349328"."PORTAL_COMPARTILHAMENTO_RESULTADO_FINANCEIRO"
(
    "ID"           INTEGER CS_INT GENERATED BY DEFAULT AS IDENTITY (START WITH 1 INCREMENT BY 1) NOT NULL,
    "ANO"          INTEGER CS_INT NOT NULL,
    "MES"          INTEGER CS_INT NOT NULL,               -- 1..12
    "INDICADOR"    NVARCHAR(30) NOT NULL,                 -- FATURAMENTO | CUSTOS | RECEITA_LIQUIDA
    "META"         DECIMAL(18,2) DEFAULT 0,               -- orcado / meta do mes
    "REALIZADO"    DECIMAL(18,2),                         -- realizado (NULL = mes ainda em aberto)
    "REV"          DECIMAL(18,2),                         -- revisao / projecao mais recente (NULL = sem revisao)
    "MOEDA"        NVARCHAR(3) DEFAULT 'BRL',
    "OBSERVACAO"   NVARCHAR(500),
    "CREATED_AT"   LONGDATE CS_LONGDATE DEFAULT CURRENT_UTCTIMESTAMP,
    "CREATED_BY"   NVARCHAR(120),
    "UPDATED_AT"   LONGDATE CS_LONGDATE,
    "UPDATED_BY"   NVARCHAR(120),
    PRIMARY KEY ("ID")
)
UNLOAD PRIORITY 5 AUTO MERGE;

-- Uma unica linha por ano/mes/indicador (chave natural do upsert).
CREATE UNIQUE INDEX "IX_PORTAL_COMP_RESFIN_CHAVE"
    ON "CLB349328"."PORTAL_COMPARTILHAMENTO_RESULTADO_FINANCEIRO" ("ANO", "MES", "INDICADOR");

CREATE INDEX "IX_PORTAL_COMP_RESFIN_ANO"
    ON "CLB349328"."PORTAL_COMPARTILHAMENTO_RESULTADO_FINANCEIRO" ("ANO");


-- =====================================================================
-- Visao de apoio: acumulado YTD por ano/indicador/mes de referencia.
-- (a aplicacao tambem calcula isso em memoria; a view fica disponivel
--  para relatorios diretos no banco)
-- =====================================================================
CREATE OR REPLACE VIEW "CLB349328"."V_PORTAL_COMPARTILHAMENTO_RESULTADO_FINANCEIRO_YTD" AS
SELECT
    r."ANO",
    r."INDICADOR",
    r."MES"                                                            AS "MES_REF",
    SUM(a."META")                                                      AS "META_YTD",
    SUM(a."REALIZADO")                                                 AS "REALIZADO_YTD",
    SUM(COALESCE(a."REV", a."REALIZADO", a."META"))                    AS "REV_YTD",
    SUM(a."REALIZADO") - SUM(a."META")                                 AS "DESVIO_YTD"
FROM "CLB349328"."PORTAL_COMPARTILHAMENTO_RESULTADO_FINANCEIRO" r
JOIN "CLB349328"."PORTAL_COMPARTILHAMENTO_RESULTADO_FINANCEIRO" a
     ON a."ANO" = r."ANO"
    AND a."INDICADOR" = r."INDICADOR"
    AND a."MES" <= r."MES"
GROUP BY r."ANO", r."INDICADOR", r."MES";
