-- =====================================================================
--  Área de atuação das EPS (tabela de suporte)
--
--  Relaciona a EPS (Empresa Prestadora de Serviço) com a estrutura
--  organizacional da distribuidora:
--     SUPERINTENDENCIA  ->  UTD  ->  SETOR  ->  MUNICIPIO
--
--  É a fonte de verdade de "qual EPS atende cada município" no gerador
--  de Carteira de Serviço: o usuário filtra por superintendência / UTD /
--  setor, os municípios disponíveis se restringem e a lista de EPS passa
--  a mostrar só as que atuam no escopo.
--
--  Uma linha por (EPS, MUNICIPIO). Um mesmo município pode ter mais de
--  uma EPS (tipos de serviço diferentes) => mais de uma linha.
--  Schema de trabalho: ajuste "CLB349328" se o seu for outro.
-- =====================================================================

CREATE COLUMN TABLE "CLB349328"."PORTAL_COMPARTILHAMENTO_EPS_ATUACAO"
(
    "ID"               INTEGER CS_INT GENERATED BY DEFAULT AS IDENTITY,
    "ID_EPS"           INTEGER NOT NULL,               -- -> PORTAL_COMPARTILHAMENTO_EPS.ID_EPS
    "SUPERINTENDENCIA" NVARCHAR(120),
    "UTD"              NVARCHAR(120),                   -- Unidade Técnica de Distribuição
    "SETOR"            NVARCHAR(120),
    "MUNICIPIO"        NVARCHAR(120) NOT NULL,
    "ATIVO"            NVARCHAR(1) DEFAULT 'S',
    "CREATED_AT"       LONGDATE CS_LONGDATE,
    "CREATED_BY"       NVARCHAR(100),
    "UPDATED_AT"       LONGDATE CS_LONGDATE,
    PRIMARY KEY ("ID")
)
UNLOAD PRIORITY 5 AUTO MERGE;

CREATE UNIQUE INDEX "IX_EPSATUACAO_EPS_MUN"
    ON "CLB349328"."PORTAL_COMPARTILHAMENTO_EPS_ATUACAO" ("ID_EPS", "MUNICIPIO");
CREATE INDEX "IX_EPSATUACAO_MUNICIPIO"
    ON "CLB349328"."PORTAL_COMPARTILHAMENTO_EPS_ATUACAO" ("MUNICIPIO");
CREATE INDEX "IX_EPSATUACAO_SUPERINT"
    ON "CLB349328"."PORTAL_COMPARTILHAMENTO_EPS_ATUACAO" ("SUPERINTENDENCIA");
CREATE INDEX "IX_EPSATUACAO_UTD"
    ON "CLB349328"."PORTAL_COMPARTILHAMENTO_EPS_ATUACAO" ("UTD");


-- Consulta típica: EPS que atendem um conjunto de municípios, com o
-- contexto organizacional.
--   SELECT A.ID_EPS, E.NOME, A.SUPERINTENDENCIA, A.UTD, A.SETOR, A.MUNICIPIO
--   FROM "CLB349328"."PORTAL_COMPARTILHAMENTO_EPS_ATUACAO" A
--   JOIN "CLB349328"."PORTAL_COMPARTILHAMENTO_EPS" E ON E.ID_EPS = A.ID_EPS
--   WHERE A.ATIVO = 'S' AND E.ATIVO = 'S'
--     AND UPPER(A.MUNICIPIO) IN (...);
