from fastapi import APIRouter, HTTPException, Path, Body, Query, File, UploadFile, Request
from typing import Any, Optional, List, Dict, Tuple
from decimal import Decimal, InvalidOperation
from datetime import datetime, date, timedelta
import hashlib
import io
import re
import pandas as pd
from pydantic import BaseModel

import main

router = APIRouter()

# Novos Entrantes endpoints

from fastapi import HTTPException, Path


def _registrar_evento_entrada(
    cursor,
    id_entrada: int,
    status_anterior: Optional[str],
    status_novo: str,
    usuario: Optional[str] = None,
    observacao: Optional[str] = None,
) -> None:
    """Grava um evento de transição de status na jornada do entrante.
    Não deve derrubar o fluxo principal se a gravação falhar."""
    try:
        cursor.execute(
            """
            INSERT INTO CLB349328.PORTAL_COMPARTILHAMENTO_HISTORICO_ENTRADA
            (
                ID_ENTRADA,
                STATUS_ANTERIOR,
                STATUS_NOVO,
                USUARIO,
                OBSERVACAO,
                DATA_EVENTO
            )
            VALUES
            (
                ?,
                ?,
                ?,
                ?,
                ?,
                CURRENT_TIMESTAMP
            )
            """,
            [id_entrada, status_anterior, status_novo, usuario or "CLB349328", observacao],
        )
    except Exception as error:
        print(f"Falha ao registrar histórico do entrante {id_entrada}: {error}")


# ------------------------------------------------------------
# Interações de contato do entrante (e-mail, ligação, WhatsApp...)
# ------------------------------------------------------------

_CANAIS_INTERACAO = {"EMAIL", "LIGACAO", "WHATSAPP", "REUNIAO", "PRESENCIAL", "OUTRO"}
_SENTIDOS_INTERACAO = {"ENVIADO", "RECEBIDO"}


def _garantir_tabela_interacao(cursor) -> None:
    """Cria PORTAL_COMPARTILHAMENTO_ENTRADA_INTERACAO na primeira vez, no mesmo
    espírito do _garantir_tabela usado em outras partes do portal. O DDL
    canônico está em sql/PORTAL_COMPARTILHAMENTO_ENTRADA_INTERACAO.sql."""
    try:
        cursor.execute("SELECT COUNT(*) FROM CLB349328.PORTAL_COMPARTILHAMENTO_ENTRADA_INTERACAO")
        cursor.fetchone()
        return
    except Exception:
        pass

    cursor.execute(
        """
        CREATE COLUMN TABLE CLB349328.PORTAL_COMPARTILHAMENTO_ENTRADA_INTERACAO
        (
            ID_INTERACAO INTEGER CS_INT GENERATED BY DEFAULT AS IDENTITY,
            ID_ENTRADA INTEGER NOT NULL,
            CANAL NVARCHAR(20) NOT NULL,
            SENTIDO NVARCHAR(10) DEFAULT 'ENVIADO',
            CONTATO NVARCHAR(200),
            ASSUNTO NVARCHAR(300),
            OBSERVACAO NVARCHAR(4000),
            USUARIO NVARCHAR(100),
            DATA_INTERACAO LONGDATE CS_LONGDATE,
            PRIMARY KEY (ID_INTERACAO)
        )
        UNLOAD PRIORITY 5 AUTO MERGE
        """
    )


def _criar_processo_para_provedor(cursor, id_provedor: int, user: str) -> Tuple[int, str]:
    """Cria um processo novo (etapa inicial, jornada em andamento) para um
    provedor já existente. Reutilizado tanto pelo fluxo de criação de
    processo a partir de um Entrante quanto pela criação direta de um novo
    processo/PN para um provedor que já tem cadastro (POST /api/provedores/{id}/processos).
    Não faz commit - quem chama decide quando confirmar a transação."""
    numero_protocolo_temporario = f"TEMP-{id_provedor}-{datetime.now().strftime('%Y%m%d%H%M%S%f')}"

    cursor.execute(
        """
        INSERT INTO CLB349328.PORTAL_COMPARTILHAMENTO_PROCESSO
        (
            ID_PROVEDOR,
            NUMERO_PROTOCOLO,
            TIPO_PROCESSO,
            STATUS_ATUAL,
            ETAPA_ATUAL,
            DT_ABERTURA
        )
        VALUES
        (
            ?,
            ?,
            'REGULARIZACAO_CADASTRAL',
            'ABERTO',
            1,
            CURRENT_TIMESTAMP
        )
        """,
        [id_provedor, numero_protocolo_temporario],
    )

    # pyhdb não possui cursor.lastrowid.
    # Primeiro tenta recuperar o ID da identidade gerada na sessão.
    try:
        cursor.execute("""
            SELECT CURRENT_IDENTITY_VALUE()
            FROM DUMMY
        """)
        resultado_id = cursor.fetchone()
        id_processo = resultado_id[0] if resultado_id else None
    except Exception:
        id_processo = None

    # Fallback: buscar o processo criado para o provedor com o protocolo temporário.
    if not id_processo:
        cursor.execute(
            """
            SELECT MAX(ID_PROCESSO)
            FROM CLB349328.PORTAL_COMPARTILHAMENTO_PROCESSO
            WHERE ID_PROVEDOR = ?
              AND NUMERO_PROTOCOLO = ?
            """,
            [id_provedor, numero_protocolo_temporario],
        )
        resultado_id = cursor.fetchone()
        id_processo = resultado_id[0] if resultado_id else None

    if not id_processo:
        raise HTTPException(
            status_code=500,
            detail="Não foi possível recuperar o ID do processo criado."
        )

    numero_protocolo = f"{datetime.now().year}-{int(id_processo):06d}"

    cursor.execute(
        """
        UPDATE CLB349328.PORTAL_COMPARTILHAMENTO_PROCESSO
           SET NUMERO_PROTOCOLO = ?
         WHERE ID_PROCESSO = ?
        """,
        [numero_protocolo, id_processo],
    )

    cursor.execute(
        """
        INSERT INTO CLB349328.PORTAL_COMPARTILHAMENTO_JORNADA
        (
            ID_PROCESSO,
            ID_ETAPA,
            STATUS_ETAPA,
            DATA_ENTRADA_ETAPA,
            RESPONSAVEL_ATUAL,
            CREATED_AT,
            CREATED_BY
        )
        VALUES
        (
            ?,
            1,
            'EM_ANDAMENTO',
            CURRENT_TIMESTAMP,
            ?,
            CURRENT_TIMESTAMP,
            ?
        )
        """,
        [id_processo, user, user],
    )

    return int(id_processo), numero_protocolo


@router.get("/api/novos-entrantes", response_model=List[dict])
def listar_novos_entrantes(
    status: Optional[str] = Query(None),
    municipio: Optional[str] = Query(None),
    cnpj: Optional[str] = Query(None)

):
    conn = None
    cursor = None
    try:
        conn = main.get_connection()
        cursor = conn.cursor()
        sql = """
            SELECT ID_ENTRADA,
                   DATA_RECEBIMENTO,
                   RAZAO_SOCIAL,
                   CNPJ,
                   MUNICIPIO,
                   QTD_POSTES,
                   POSSUI_GEOS,
                   STATUS_ENTRADA,
                   RESPONSAVEL_ANALISE,
                   PRAZO_ANALISE
            FROM CLB349328.PORTAL_COMPARTILHAMENTO_ENTRADA
            WHERE 1=1
        """
        params = []
        if status:
            sql += " AND STATUS_ENTRADA = ?"
            params.append(status)
        if municipio:
            sql += " AND MUNICIPIO = ?"
            params.append(municipio)
        if cnpj:
            sql += " AND CNPJ LIKE ?"
            params.append(f"%{cnpj}%")
        cursor.execute(sql, params)
        columns = [col[0] for col in cursor.description]
        rows = cursor.fetchall()
        result = [dict(zip(columns, row)) for row in rows]
        return result
    finally:
        if cursor:
            cursor.close()
        if conn:
            conn.close()

@router.get("/api/novos-entrantes/entrada/{id}", response_model=dict)
def obter_entrada(
    id: int = Path(..., alias="id"),
):
    conn = None
    cursor = None
    try:
        conn = main.get_connection()
        cursor = conn.cursor()
        cursor.execute(
            """
            SELECT *
            FROM CLB349328.PORTAL_COMPARTILHAMENTO_ENTRADA
            WHERE ID_ENTRADA = ?
            """,
            [id],
        )
        row = cursor.fetchone()
        if not row:
            raise HTTPException(status_code=404, detail="Entrada não encontrada")
        columns = [col[0] for col in cursor.description]
        return dict(zip(columns, row))
    finally:
        if cursor:
            cursor.close()
        if conn:
            conn.close()


@router.get("/api/novos-entrantes/entrada/{id}/historico", response_model=List[dict])
def obter_historico_entrada(
    id: int = Path(..., alias="id"),
):
    """Linha do tempo de transições de status do entrante (jornada)."""
    conn = None
    cursor = None
    try:
        conn = main.get_connection()
        cursor = conn.cursor()
        cursor.execute(
            """
            SELECT
                ID_HISTORICO,
                ID_ENTRADA,
                STATUS_ANTERIOR,
                STATUS_NOVO,
                USUARIO,
                OBSERVACAO,
                DATA_EVENTO
            FROM CLB349328.PORTAL_COMPARTILHAMENTO_HISTORICO_ENTRADA
            WHERE ID_ENTRADA = ?
            ORDER BY DATA_EVENTO ASC, ID_HISTORICO ASC
            """,
            [id],
        )
        columns = [col[0] for col in cursor.description]
        return [dict(zip(columns, row)) for row in cursor.fetchall()]
    finally:
        if cursor:
            cursor.close()
        if conn:
            conn.close()


@router.get("/api/novos-entrantes/entrada/{id}/interacoes", response_model=List[dict])
def listar_interacoes_entrada(id: int = Path(..., alias="id")):
    """Interações de contato registradas para o entrante."""
    conn = None
    cursor = None
    try:
        conn = main.get_connection()
        cursor = conn.cursor()
        _garantir_tabela_interacao(cursor)
        cursor.execute(
            """
            SELECT
                ID_INTERACAO,
                ID_ENTRADA,
                CANAL,
                SENTIDO,
                CONTATO,
                ASSUNTO,
                OBSERVACAO,
                USUARIO,
                DATA_INTERACAO
            FROM CLB349328.PORTAL_COMPARTILHAMENTO_ENTRADA_INTERACAO
            WHERE ID_ENTRADA = ?
            ORDER BY DATA_INTERACAO ASC, ID_INTERACAO ASC
            """,
            [id],
        )
        columns = [col[0] for col in cursor.description]
        return [dict(zip(columns, row)) for row in cursor.fetchall()]
    finally:
        if cursor:
            cursor.close()
        if conn:
            conn.close()


@router.post("/api/novos-entrantes/entrada/{id}/interacoes", response_model=dict)
def registrar_interacao_entrada(
    id: int = Path(..., alias="id"),
    payload: dict = Body(...),
):
    """Registra uma interação de contato com o entrante (aparece na timeline)."""
    canal = str(payload.get("canal") or "").strip().upper()
    sentido = str(payload.get("sentido") or "ENVIADO").strip().upper()

    if canal not in _CANAIS_INTERACAO:
        raise HTTPException(
            status_code=400,
            detail=f"canal deve ser um de: {', '.join(sorted(_CANAIS_INTERACAO))}",
        )
    if sentido not in _SENTIDOS_INTERACAO:
        raise HTTPException(status_code=400, detail="sentido deve ser ENVIADO ou RECEBIDO")

    def _limpo(valor: Any) -> Optional[str]:
        texto = str(valor).strip() if valor is not None else ""
        return texto or None

    conn = None
    cursor = None
    try:
        conn = main.get_connection()
        cursor = conn.cursor()
        _garantir_tabela_interacao(cursor)

        cursor.execute(
            "SELECT 1 FROM CLB349328.PORTAL_COMPARTILHAMENTO_ENTRADA WHERE ID_ENTRADA = ?",
            [id],
        )
        if not cursor.fetchone():
            raise HTTPException(status_code=404, detail="Entrada não encontrada")

        cursor.execute(
            """
            INSERT INTO CLB349328.PORTAL_COMPARTILHAMENTO_ENTRADA_INTERACAO
            (
                ID_ENTRADA,
                CANAL,
                SENTIDO,
                CONTATO,
                ASSUNTO,
                OBSERVACAO,
                USUARIO,
                DATA_INTERACAO
            )
            VALUES (?, ?, ?, ?, ?, ?, ?, CURRENT_TIMESTAMP)
            """,
            [
                id,
                canal,
                sentido,
                _limpo(payload.get("contato")),
                _limpo(payload.get("assunto")),
                _limpo(payload.get("observacao")),
                _limpo(payload.get("usuario")) or "CLB349328",
            ],
        )
        conn.commit()
        return {"success": True}
    except HTTPException:
        raise
    finally:
        if cursor:
            cursor.close()
        if conn:
            conn.close()


@router.get("/api/novos-entrantes/entrada/{id}/timeline", response_model=List[dict])
def obter_timeline_entrada(id: int = Path(..., alias="id")):
    """Timeline unificada: transições de estágio + interações de contato,
    em ordem cronológica. Consumida por components/comercial/timeline-entrante.tsx."""
    conn = None
    cursor = None
    try:
        conn = main.get_connection()
        cursor = conn.cursor()
        _garantir_tabela_interacao(cursor)

        cursor.execute(
            """
            SELECT STATUS_ANTERIOR, STATUS_NOVO, OBSERVACAO, USUARIO, DATA_EVENTO
            FROM CLB349328.PORTAL_COMPARTILHAMENTO_HISTORICO_ENTRADA
            WHERE ID_ENTRADA = ?
            """,
            [id],
        )
        eventos: List[dict] = [
            {
                "tipo": "STATUS",
                "data": row[4],
                "status_anterior": row[0],
                "status_novo": row[1],
                "detalhe": row[2],
                "usuario": row[3],
            }
            for row in cursor.fetchall()
        ]

        cursor.execute(
            """
            SELECT CANAL, SENTIDO, CONTATO, ASSUNTO, OBSERVACAO, USUARIO, DATA_INTERACAO
            FROM CLB349328.PORTAL_COMPARTILHAMENTO_ENTRADA_INTERACAO
            WHERE ID_ENTRADA = ?
            """,
            [id],
        )
        eventos.extend(
            {
                "tipo": "CONTATO",
                "data": row[6],
                "titulo": row[3] or "Contato registrado",
                "canal": row[0],
                "sentido": row[1],
                "contato": row[2],
                "detalhe": row[4],
                "usuario": row[5],
            }
            for row in cursor.fetchall()
        )

        eventos.sort(key=lambda evento: (evento["data"] is None, evento["data"]))
        return eventos
    finally:
        if cursor:
            cursor.close()
        if conn:
            conn.close()


# ------------------------------------------------------------
# Carteira de Análise (kanban por analista/prazo)
# ------------------------------------------------------------

class AtribuirAnaliseRequest(BaseModel):
    responsavel: Optional[str] = None
    prazo: Optional[str] = None


@router.get("/api/novos-entrantes/carteira", response_model=List[dict])
def listar_carteira_analise():
    """Entrantes elegíveis para a fila de análise (ainda não viraram
    provedor/processo nem foram descartados)."""
    conn = None
    cursor = None
    try:
        conn = main.get_connection()
        cursor = conn.cursor()
        cursor.execute(
            """
            SELECT
                ID_ENTRADA,
                RAZAO_SOCIAL,
                NOME_FANTASIA,
                CNPJ,
                MUNICIPIO,
                UF,
                STATUS_ENTRADA,
                DATA_RECEBIMENTO,
                RESPONSAVEL_ANALISE,
                PRAZO_ANALISE,
                DATA_ATRIBUICAO,
                PRIORIDADE
            FROM CLB349328.PORTAL_COMPARTILHAMENTO_ENTRADA
            WHERE ATIVO = 'S'
              AND STATUS_ENTRADA IN ('NOVO', 'ANALISADO')
            ORDER BY PRAZO_ANALISE ASC, DATA_RECEBIMENTO ASC
            """
        )
        columns = [col[0] for col in cursor.description]
        return [dict(zip(columns, row)) for row in cursor.fetchall()]
    finally:
        if cursor:
            cursor.close()
        if conn:
            conn.close()


def _somente_data(valor):
    """Normaliza um valor de data/timestamp do HANA (ou string ISO, no caso
    dos testes) para datetime.date, pra comparar prazo x resolução sem se
    importar com o horário."""
    if isinstance(valor, datetime):
        return valor.date()
    if isinstance(valor, date):
        return valor
    if isinstance(valor, str):
        return datetime.fromisoformat(valor[:10]).date()
    return None


@router.get("/api/novos-entrantes/sla-analise", response_model=dict)
def obter_sla_analise():
    """Taxa histórica de cumprimento do prazo atribuído (PRAZO_ANALISE) nos
    entrantes já resolvidos (viraram provedor ou foram descartados). A data
    de resolução vem do primeiro evento de saída da fila de análise em
    HISTORICO_ENTRADA, já que ENTRADA não guarda esse timestamp."""
    conn = None
    cursor = None
    try:
        conn = main.get_connection()
        cursor = conn.cursor()
        cursor.execute(
            """
            SELECT E.PRAZO_ANALISE, MIN(H.DATA_EVENTO) AS DATA_RESOLUCAO
            FROM CLB349328.PORTAL_COMPARTILHAMENTO_ENTRADA E
            INNER JOIN CLB349328.PORTAL_COMPARTILHAMENTO_HISTORICO_ENTRADA H
                ON H.ID_ENTRADA = E.ID_ENTRADA
               AND H.STATUS_NOVO IN ('PROVEDOR_CRIADO', 'DESCARTADO')
            WHERE E.PRAZO_ANALISE IS NOT NULL
            GROUP BY E.ID_ENTRADA, E.PRAZO_ANALISE
            """
        )
        linhas = cursor.fetchall()

        total = len(linhas)
        dentro_prazo = sum(
            1 for prazo, resolucao in linhas
            if _somente_data(resolucao) is not None and _somente_data(resolucao) <= _somente_data(prazo)
        )
        fora_prazo = total - dentro_prazo
        taxa = round((dentro_prazo / total) * 100, 1) if total > 0 else 0

        return {
            "total_avaliados": total,
            "dentro_prazo": dentro_prazo,
            "fora_prazo": fora_prazo,
            "taxa_cumprimento_sla": taxa,
        }
    finally:
        if cursor:
            cursor.close()
        if conn:
            conn.close()


@router.get("/api/novos-entrantes/analistas", response_model=List[dict])
def listar_analistas():
    """Lista leve de usuários ativos para o seletor de responsável pela
    análise (endpoint próprio porque /api/admin/usuarios é restrito ao
    perfil Administrador)."""
    conn = None
    cursor = None
    try:
        conn = main.get_connection()
        cursor = conn.cursor()
        cursor.execute(
            """
            SELECT LOGIN, NOME
            FROM CLB349328.PORTAL_COMPARTILHAMENTO_USUARIO
            WHERE COALESCE(STATUS, 'A') = 'A'
            ORDER BY NOME
            """
        )
        columns = [col[0] for col in cursor.description]
        return [dict(zip(columns, row)) for row in cursor.fetchall()]
    finally:
        if cursor:
            cursor.close()
        if conn:
            conn.close()


@router.patch("/api/novos-entrantes/entrada/{id}/atribuir", response_model=dict)
def atribuir_analise(
    dados: AtribuirAnaliseRequest,
    id: int = Path(..., alias="id"),
):
    """Define/troca o responsável e o prazo de análise de um entrante, sem
    mexer no STATUS_ENTRADA - diferente do PATCH genérico de edição, que
    auto-transiciona NOVO -> ANALISADO ao salvar qualquer alteração."""
    conn = None
    cursor = None
    user = "CLB349328"
    try:
        conn = main.get_connection()
        cursor = conn.cursor()

        cursor.execute(
            "SELECT STATUS_ENTRADA FROM CLB349328.PORTAL_COMPARTILHAMENTO_ENTRADA WHERE ID_ENTRADA = ?",
            [id],
        )
        registro = cursor.fetchone()
        if not registro:
            raise HTTPException(status_code=404, detail="Entrante não encontrado")

        status_atual = registro[0]
        responsavel = (dados.responsavel or "").strip() or None
        prazo = (dados.prazo or "").strip() or None

        cursor.execute(
            """
            UPDATE CLB349328.PORTAL_COMPARTILHAMENTO_ENTRADA
               SET RESPONSAVEL_ANALISE = ?,
                   PRAZO_ANALISE = TO_DATE(?),
                   DATA_ATRIBUICAO = CURRENT_TIMESTAMP,
                   UPDATED_AT = CURRENT_TIMESTAMP,
                   UPDATED_BY = ?
             WHERE ID_ENTRADA = ?
            """,
            [responsavel, prazo, user, id],
        )

        observacao = (
            f"Atribuído a {responsavel}, prazo {prazo or 'não definido'}"
            if responsavel
            else "Responsável removido da carteira de análise"
        )
        _registrar_evento_entrada(cursor, id, status_atual, status_atual, usuario=user, observacao=observacao)

        conn.commit()

        return {
            "success": True,
            "id_entrada": id,
            "responsavel_analise": responsavel,
            "prazo_analise": prazo,
        }
    except HTTPException:
        if conn:
            conn.rollback()
        raise
    except Exception as error:
        if conn:
            conn.rollback()
        raise HTTPException(status_code=500, detail=f"Erro ao atribuir análise: {str(error)}")
    finally:
        if cursor:
            cursor.close()
        if conn:
            conn.close()


@router.post("/api/novos-entrantes/entrada/{id}/criar-processo", response_model=dict)
def criar_processo(
    id: int = Path(..., alias="id"),
):
    conn = None
    cursor = None
    user = "CLB349328"

    try:
        conn = main.get_connection()
        cursor = conn.cursor()

        # 1) Buscar Entrante
        cursor.execute(
            """
            SELECT
                ID_ENTRADA,
                STATUS_ENTRADA,
                CNPJ,
                ID_PROCESSO
            FROM CLB349328.PORTAL_COMPARTILHAMENTO_ENTRADA
            WHERE ID_ENTRADA = ?
              AND ATIVO = 'S'
            """,
            [id],
        )
        entrada = cursor.fetchone()

        if not entrada:
            raise HTTPException(
                status_code=404,
                detail="Entrada não encontrada"
            )

        id_entrada, status_entrada, cnpj, id_processo_existente = entrada

        # 2) Bloquear novo processo se já houver processo vinculado
        if id_processo_existente:
            raise HTTPException(
                status_code=409,
                detail="Este Entrante já possui Processo criado. Não é permitido criar processo duplicado."
            )

        if status_entrada == "PROCESSO_CRIADO":
            raise HTTPException(
                status_code=409,
                detail="Este Entrante já está com status PROCESSO_CRIADO."
            )

        # 3) Processo só pode ser criado depois do Provedor
        if status_entrada != "PROVEDOR_CRIADO":
            raise HTTPException(
                status_code=400,
                detail="Para criar o processo, o Entrante precisa estar com status PROVEDOR_CRIADO."
            )

        # 4) Buscar Provedor existente pelo CNPJ do Entrante
        cursor.execute(
            """
            SELECT ID_PROVEDOR
            FROM CLB349328.PORTAL_COMPARTILHAMENTO_PROVEDOR
            WHERE CNPJ = ?
            """,
            [cnpj],
        )
        provedor = cursor.fetchone()

        if not provedor:
            raise HTTPException(
                status_code=400,
                detail="Não existe Provedor cadastrado para o CNPJ deste Entrante. Crie o Provedor antes de criar o Processo."
            )

        id_provedor = provedor[0]

        # 5-7) Criar Processo + Jornada inicial usando o Provedor existente
        id_processo, numero_protocolo = _criar_processo_para_provedor(cursor, id_provedor, user)

        # 8) Atualizar Entrante com ID_PROCESSO e status final do fluxo
        cursor.execute(
            """
            UPDATE CLB349328.PORTAL_COMPARTILHAMENTO_ENTRADA
               SET STATUS_ENTRADA = 'PROCESSO_CRIADO',
                   ID_PROCESSO = ?,
                   UPDATED_AT = CURRENT_TIMESTAMP,
                   UPDATED_BY = ?
             WHERE ID_ENTRADA = ?
            """,
            [id_processo, user, id_entrada],
        )

        _registrar_evento_entrada(cursor, id_entrada, "PROVEDOR_CRIADO", "PROCESSO_CRIADO", usuario=user)

        conn.commit()

        return {
            "success": True,
            "id_entrada": id_entrada,
            "id_provedor": id_provedor,
            "processoCriado": id_processo,
                "id_processo": id_processo,
            "numeroProtocolo": numero_protocolo,
            "mensagem": "Processo criado com sucesso"
        }

    except HTTPException:
        if conn:
            conn.rollback()
        raise

    except Exception as e:
        if conn:
            conn.rollback()
        raise HTTPException(
            status_code=500,
            detail=str(e)
        )

    finally:
        if cursor:
            cursor.close()
        if conn:
            conn.close()




@router.patch("/api/novos-entrantes/entrada/{id}/descartar", response_model=dict)
def descartar_entrada(
    id: int = Path(..., alias="id"),
    payload: dict = Body(...)
):
    motivo = payload.get("motivo")
    if not motivo:
        raise HTTPException(
            status_code=400, detail="O campo motivo é obrigatório para descarte"
        )

    conn = None
    cursor = None
    try:
        conn = main.get_connection()
        cursor = conn.cursor()

        cursor.execute(
            """
            SELECT STATUS_ENTRADA
            FROM CLB349328.PORTAL_COMPARTILHAMENTO_ENTRADA
            WHERE ID_ENTRADA = ?
            """,
            [id],
        )
        registro = cursor.fetchone()
        status_anterior = registro[0] if registro else None

        cursor.execute(
            """
            UPDATE CLB349328.PORTAL_COMPARTILHAMENTO_ENTRADA
            SET STATUS_ENTRADA = 'DESCARTADO',
                MOTIVO_DESCARTE = ?,
                DELETED_AT = CURRENT_TIMESTAMP,
                DELETED_BY = ?
            WHERE ID_ENTRADA = ?
            """,
            [motivo, "CLB349328", id],
        )

        _registrar_evento_entrada(cursor, id, status_anterior, "DESCARTADO", observacao=motivo)

        conn.commit()
        return {"success": True}
    finally:
        if cursor:
            cursor.close()
        if conn:
            conn.close()


# ------------------------------------------------------------
# Helpers específicos da importação Forms
# ------------------------------------------------------------

def _texto(valor: Any) -> Optional[str]:
    if valor is None:
        return None
    try:
        if pd.isna(valor):
            return None
    except Exception:
        pass

    texto = str(valor).strip()
    if texto == "" or texto.lower() in ["nan", "none", "null"]:
        return None
    return texto

def _normalizar_uf(valor):

    texto = _texto(valor)

    if not texto:
        return None

    mapa = {
        "ACRE": "AC",
        "ALAGOAS": "AL",
        "AMAPA": "AP",
        "AMAPÁ": "AP",
        "AMAZONAS": "AM",
        "BAHIA": "BA",
        "CEARA": "CE",
        "CEARÁ": "CE",
        "DISTRITO FEDERAL": "DF",
        "ESPIRITO SANTO": "ES",
        "ESPÍRITO SANTO": "ES",
        "GOIAS": "GO",
        "GOIÁS": "GO",
        "MARANHAO": "MA",
        "MARANHÃO": "MA",
        "MATO GROSSO": "MT",
        "MATO GROSSO DO SUL": "MS",
        "MINAS GERAIS": "MG",
        "PARA": "PA",
        "PARÁ": "PA",
        "PARAIBA": "PB",
        "PARAÍBA": "PB",
        "PARANA": "PR",
        "PARANÁ": "PR",
        "PERNAMBUCO": "PE",
        "PIAUI": "PI",
        "PIAUÍ": "PI",
        "RIO DE JANEIRO": "RJ",
        "RIO GRANDE DO NORTE": "RN",
        "RIO GRANDE DO SUL": "RS",
        "RONDONIA": "RO",
        "RONDÔNIA": "RO",
        "RORAIMA": "RR",
        "SANTA CATARINA": "SC",
        "SAO PAULO": "SP",
        "SÃO PAULO": "SP",
        "SERGIPE": "SE",
        "TOCANTINS": "TO"
    }

    texto = texto.strip().upper()

    return mapa.get(texto, texto[:2])


def _somente_digitos(valor: Any, tamanho: Optional[int] = None) -> Optional[str]:
    texto = _texto(valor)
    if not texto:
        return None

    # Corrige valores vindos em notacao cientifica pelo pandas/excel
    try:
        if "e" in texto.lower():
            texto = format(Decimal(texto), "f")
    except (InvalidOperation, ValueError):
        pass

    if texto.endswith(".0"):
        texto = texto[:-2]

    digitos = re.sub(r"\D", "", texto)
    if not digitos:
        return None

    if tamanho and len(digitos) <= tamanho:
        digitos = digitos.zfill(tamanho)

    return digitos


def _inteiro(valor: Any) -> int:
    texto = _texto(valor)
    if not texto:
        return 0

    texto = texto.replace(".", "").replace(",", ".")

    try:
        return int(float(texto))
    except Exception:
        return 0


def _sim_nao(valor):

    texto = _texto(valor)

    if not texto:
        return None

    texto_upper = texto.upper().strip()

    if texto_upper in [
        "S",
        "SIM",
        "TRUE",
        "1",
        "YES"
    ]:
        return "S"

    if texto_upper in [
        "N",
        "NAO",
        "NÃO",
        "FALSE",
        "0",
        "NO"
    ]:
        return "N"

    if texto_upper in [
        "NAO SEI",
        "NÃO SEI"
    ]:
        return "I"

    return None


def _timestamp_forms(valor: Any):
    texto = _texto(valor)
    if not texto:
        return None

    try:
        data = pd.to_datetime(
            texto,
            format="%m/%d/%Y %I:%M %p",
            errors="coerce",
        )

        if pd.isna(data):
            data = pd.to_datetime(texto, errors="coerce")

        if pd.isna(data):
            return None

        return data.to_pydatetime()
    except Exception:
        return None


def _get(row: Dict[str, Any], coluna: str) -> Any:
    return row.get(coluna)


def _gerar_id_forms(row: Dict[str, Any]) -> str:
    base = "|".join([
        str(_get(row, "Hora de conclusão") or ""),
        str(_get(row, "Razão Social") or ""),
        str(_get(row, "CNPJ") or ""),
        str(_get(row, "E-mail") or ""),
    ])
    return hashlib.sha256(base.encode("utf-8")).hexdigest()[:60]


def _mapear_linha_forms(row: Dict[str, Any]) -> Dict[str, Any]:
    return {
        "ID_FORMS": _gerar_id_forms(row),
        "DATA_RECEBIMENTO": _timestamp_forms(_get(row, "Hora de conclusão")) or datetime.now(),
        "RAZAO_SOCIAL": _texto(_get(row, "Razão Social")),
        "NOME_FANTASIA": _texto(_get(row, "Nome Fantasia")),
        "CNPJ": _somente_digitos(_get(row, "CNPJ"), 14),
        "LOGRADOURO": _texto(_get(row, "Rua do endereço sede")),
        "NUMERO_ENDERECO": _texto(_get(row, "Número do endereço sede")),
        "CEP": _somente_digitos(_get(row, "CEP do endereço sede"), 8),
        "BAIRRO": _texto(_get(row, "Bairro do endereço sede")),
        "MUNICIPIO": _texto(_get(row, "Município do endereço sede")),
        "UF": _normalizar_uf(_get(row, "Estado do endereço sede")),
        "EMAIL_CONTATO": _texto(_get(row, "E-mail")),
        "TELEFONE_CONTATO": _somente_digitos(_get(row, "Telefone")),
        "INSCRICAO_MUNICIPAL": _texto(_get(row, "Inscrição Municipal")),
        "INSCRICAO_ESTADUAL": _texto(_get(row, "Inscrição Estadual")),
        "PROCESSO_SEI_ANATEL": _texto(_get(row, "Processo SEI da ANATEL (Outorga)")),
        "POSSUI_GEOS": _sim_nao(_get(row, "A empresa possui cadastro no Sistema GEOS?")),
        "POSSUI_OS_GEOS": _sim_nao(_get(row, "Existem Ordens de Serviços despachadas no Sistema GEOS?")),
        "NOME_RESPONSAVEL": _texto(_get(row, "Nome completo")),
        "RG_RESPONSAVEL": _somente_digitos(_get(row, "RG")),
        "CPF_RESPONSAVEL": _somente_digitos(_get(row, "CPF"), 11),
        "TELEFONE_RESPONSAVEL": _somente_digitos(_get(row, "Telefone Resp. Legal")),
        "EMAIL_RESPONSAVEL": _texto(_get(row, "E-mail Resp. Legal")),
        "REDE_FIBRA": _sim_nao(_get(row, "As redes utilizadas são de fibra ótica?")),
        "ATENDE_DIS_NOR_056": _sim_nao(_get(row, "As redes utilizadas cumprem o padrão técnico estabelecido na norma DIS-NOR-056?")),
        "QTD_MUNICIPIOS": _inteiro(_get(row, "As ocupações estão presentes em quantos municípios?")),
        "MUNICIPIOS_ATUACAO": _texto(_get(row, "Quais os municípios de atuação?")),
        "QTD_POSTES": _inteiro(_get(row, "Quantidade de postes ocupados:")),
        "INFORMACOES_ADICIONAIS": _texto(_get(row, "Informações adicionais/dúvidas")),
        "ACEITE_DECLARACAO": _sim_nao(_get(row, "Declaro conhecimento sobre as informações citadas acima e comprometo-me em cumprir os prazos estabelecidos.")),
    }


# ------------------------------------------------------------
# GET /api/novos-entrantes/consolidado
# Cards consolidados da tela Importacao Forms
# ------------------------------------------------------------

@router.get("/api/novos-entrantes/consolidado")
def consolidado_novos_entrantes():

    conn = None
    cursor = None

    try:
        conn = main.get_connection()
        cursor = conn.cursor()

        cursor.execute(
            """
            SELECT
                (SELECT COUNT(*)
                   FROM CLB349328.PORTAL_COMPARTILHAMENTO_IMPORTACAO_FORMS) AS TOTAL_IMPORTACOES,
                (SELECT COUNT(*)
                   FROM CLB349328.PORTAL_COMPARTILHAMENTO_ENTRADA
                  WHERE ATIVO = 'S') AS REGISTROS_PROCESSADOS,
                (SELECT COALESCE(SUM(REGISTROS_REJEITADOS), 0)
                   FROM CLB349328.PORTAL_COMPARTILHAMENTO_IMPORTACAO_FORMS) AS TOTAL_REJEITADOS,
                (SELECT MAX(DATA_IMPORTACAO)
                   FROM CLB349328.PORTAL_COMPARTILHAMENTO_IMPORTACAO_FORMS) AS ULTIMA_IMPORTACAO,
                (SELECT COUNT(*)
                   FROM CLB349328.PORTAL_COMPARTILHAMENTO_ENTRADA
                  WHERE ATIVO = 'S'
                    AND STATUS_ENTRADA = 'NOVO') AS NOVOS_ENTRANTES,
                (SELECT COUNT(*)
                   FROM CLB349328.PORTAL_COMPARTILHAMENTO_ENTRADA
                  WHERE ATIVO = 'S'
                    AND STATUS_ENTRADA = 'PROVEDOR_CRIADO') AS PROVEDOR_CRIADO,
                (SELECT COUNT(*)
                   FROM CLB349328.PORTAL_COMPARTILHAMENTO_ENTRADA
                  WHERE STATUS_ENTRADA = 'DESCARTADO') AS DESCARTADOS
            FROM DUMMY
            """
        )

        columns = [col[0] for col in cursor.description]
        rows = cursor.fetchall()
        return [dict(zip(columns, row)) for row in rows]

    finally:
        if cursor:
            cursor.close()
        if conn:
            conn.close()


# ------------------------------------------------------------
# GET /api/novos-entrantes/importacoes
# Historico de importacoes da tela Importacao Forms
# ------------------------------------------------------------

@router.get("/api/novos-entrantes/importacoes")
def listar_importacoes_forms():
    conn = None
    cursor = None

    try:
        conn = main.get_connection()
        cursor = conn.cursor()

        cursor.execute(
            """
            SELECT
                ID,
                NOME_ARQUIVO,
                DATA_IMPORTACAO,
                USUARIO_IMPORTACAO,
                REGISTROS_LIDOS,
                REGISTROS_INSERIDOS,
                REGISTROS_ATUALIZADOS,
                REGISTROS_REJEITADOS,
                STATUS_IMPORTACAO
            FROM CLB349328.PORTAL_COMPARTILHAMENTO_IMPORTACAO_FORMS
            ORDER BY DATA_IMPORTACAO DESC
            """
        )

        columns = [col[0] for col in cursor.description]
        rows = cursor.fetchall()
        return [dict(zip(columns, row)) for row in rows]

    finally:
        if cursor:
            cursor.close()
        if conn:
            conn.close()


# ------------------------------------------------------------
# GET /api/novos-entrantes/registros
# Grid inferior da tela Importacao Forms
# ------------------------------------------------------------

@router.get("/api/novos-entrantes/registros")
def listar_registros_forms(
    search: Optional[str] = Query(None),
    status: Optional[str] = Query(None),
    municipio: Optional[str] = Query(None),
):
    conn = None
    cursor = None

    try:
        conn = main.get_connection()
        cursor = conn.cursor()

        sql = """
            SELECT
                ID_ENTRADA,
                DATA_RECEBIMENTO,
                DATA_IMPORTACAO,
                RAZAO_SOCIAL,
                NOME_FANTASIA,
                CNPJ,
                MUNICIPIO,
                UF,
                EMAIL_CONTATO,
                TELEFONE_CONTATO,
                QTD_POSTES,
                POSSUI_GEOS,
                POSSUI_OS_GEOS,
                STATUS_ENTRADA,
                CREATED_BY
            FROM CLB349328.PORTAL_COMPARTILHAMENTO_ENTRADA
            WHERE ATIVO = 'S'
        """
        params: List[Any] = []

        if status:
            sql += " AND STATUS_ENTRADA = ?"
            params.append(status)

        if municipio:
            sql += " AND UPPER(MUNICIPIO) LIKE UPPER(?)"
            params.append(f"%{municipio}%")

        if search:
            sql += """
                AND (
                    UPPER(RAZAO_SOCIAL) LIKE UPPER(?)
                    OR UPPER(NOME_FANTASIA) LIKE UPPER(?)
                    OR CNPJ LIKE ?
                    OR UPPER(MUNICIPIO) LIKE UPPER(?)
                    OR UPPER(STATUS_ENTRADA) LIKE UPPER(?)
                )
            """
            termo = f"%{search}%"
            params.extend([termo, termo, termo, termo, termo])

        sql += " ORDER BY DATA_RECEBIMENTO DESC, ID_ENTRADA DESC"

        cursor.execute(sql, params)
        columns = [col[0] for col in cursor.description]
        rows = cursor.fetchall()
        return [dict(zip(columns, row)) for row in rows]

    finally:
        if cursor:
            cursor.close()
        if conn:
            conn.close()


# ------------------------------------------------------------
# POST /api/novos-entrantes/importar
# Importacao manual do CSV exportado do Microsoft Forms
# ------------------------------------------------------------

@router.post("/api/novos-entrantes/importar")
async def importar_novos_entrantes_forms(
    file: UploadFile = File(...),
):
    user = "CLB349328"
    conn = None
    cursor = None

    registros_lidos = 0
    registros_inseridos = 0
    registros_atualizados = 0
    registros_rejeitados = 0
    erros: List[Dict[str, Any]] = []

    try:
        conteudo = await file.read()

        df = pd.read_csv(
            io.BytesIO(conteudo),
            encoding="utf-8-sig",
            sep=None,
            engine="python",
        )

        colunas_obrigatorias = [
            "Razão Social",
            "CNPJ",
            "Município do endereço sede",
            "Quantidade de postes ocupados:",
        ]

        colunas_ausentes = [col for col in colunas_obrigatorias if col not in df.columns]
        if colunas_ausentes:
            raise HTTPException(
                status_code=400,
                detail={
                    "message": "CSV fora do layout esperado do Forms.",
                    "colunas_ausentes": colunas_ausentes,
                },
            )

        conn = main.get_connection()
        cursor = conn.cursor()

        for index, linha in df.iterrows():
            registros_lidos += 1
            row = linha.to_dict()
            dados = _mapear_linha_forms(row)

            if not dados["RAZAO_SOCIAL"] or not dados["CNPJ"]:
                registros_rejeitados += 1
                erros.append({
                    "linha": int(index) + 2,
                    "motivo": "Razão Social ou CNPJ não informado.",
                })
                continue

            cursor.execute(
                """
                SELECT ID_ENTRADA
                FROM CLB349328.PORTAL_COMPARTILHAMENTO_ENTRADA
                WHERE CNPJ = ?
                  AND ATIVO = 'S'
                ORDER BY ID_ENTRADA DESC
                LIMIT 1
                """,
                [dados["CNPJ"]],
            )
            existente = cursor.fetchone()

            if existente:
                registros_rejeitados += 1
                erros.append({
                    "linha": int(index) + 2,
                    "motivo": "Entrante com este CNPJ já existe.",
                })
                continue
            else:
                cursor.execute(
                    """
                    INSERT INTO CLB349328.PORTAL_COMPARTILHAMENTO_ENTRADA
                    (
                        ID_FORMS,
                        DATA_RECEBIMENTO,
                        DATA_IMPORTACAO,
                        STATUS_ENTRADA,
                        RAZAO_SOCIAL,
                        NOME_FANTASIA,
                        CNPJ,
                        LOGRADOURO,
                        NUMERO_ENDERECO,
                        CEP,
                        BAIRRO,
                        MUNICIPIO,
                        UF,
                        EMAIL_CONTATO,
                        TELEFONE_CONTATO,
                        INSCRICAO_MUNICIPAL,
                        INSCRICAO_ESTADUAL,
                        PROCESSO_SEI_ANATEL,
                        POSSUI_GEOS,
                        POSSUI_OS_GEOS,
                        NOME_RESPONSAVEL,
                        RG_RESPONSAVEL,
                        CPF_RESPONSAVEL,
                        TELEFONE_RESPONSAVEL,
                        EMAIL_RESPONSAVEL,
                        REDE_FIBRA,
                        ATENDE_DIS_NOR_056,
                        QTD_MUNICIPIOS,
                        MUNICIPIOS_ATUACAO,
                        QTD_POSTES,
                        INFORMACOES_ADICIONAIS,
                        ACEITE_DECLARACAO,
                        CREATED_AT,
                        CREATED_BY,
                        ATIVO
                    )
                    VALUES
                    (
                        ?, ?, CURRENT_TIMESTAMP, 'NOVO',
                        ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?,
                        CURRENT_TIMESTAMP, ?, 'S'
                    )
                    """,
                    [
                        dados["ID_FORMS"],
                        dados["DATA_RECEBIMENTO"],
                        dados["RAZAO_SOCIAL"],
                        dados["NOME_FANTASIA"],
                        dados["CNPJ"],
                        dados["LOGRADOURO"],
                        dados["NUMERO_ENDERECO"],
                        dados["CEP"],
                        dados["BAIRRO"],
                        dados["MUNICIPIO"],
                        dados["UF"],
                        dados["EMAIL_CONTATO"],
                        dados["TELEFONE_CONTATO"],
                        dados["INSCRICAO_MUNICIPAL"],
                        dados["INSCRICAO_ESTADUAL"],
                        dados["PROCESSO_SEI_ANATEL"],
                        dados["POSSUI_GEOS"],
                        dados["POSSUI_OS_GEOS"],
                        dados["NOME_RESPONSAVEL"],
                        dados["RG_RESPONSAVEL"],
                        dados["CPF_RESPONSAVEL"],
                        dados["TELEFONE_RESPONSAVEL"],
                        dados["EMAIL_RESPONSAVEL"],
                        dados["REDE_FIBRA"],
                        dados["ATENDE_DIS_NOR_056"],
                        dados["QTD_MUNICIPIOS"],
                        dados["MUNICIPIOS_ATUACAO"],
                        dados["QTD_POSTES"],
                        dados["INFORMACOES_ADICIONAIS"],
                        dados["ACEITE_DECLARACAO"],
                        user,
                    ],
                )

                registros_inseridos += 1

        status_importacao = "SUCESSO"
        if registros_rejeitados > 0 and (registros_inseridos > 0 or registros_atualizados > 0):
            status_importacao = "SUCESSO_PARCIAL"
        elif registros_rejeitados > 0 and registros_inseridos == 0 and registros_atualizados == 0:
            status_importacao = "ERRO"

        cursor.execute(
            """
            INSERT INTO CLB349328.PORTAL_COMPARTILHAMENTO_IMPORTACAO_FORMS
            (
                NOME_ARQUIVO,
                DATA_IMPORTACAO,
                USUARIO_IMPORTACAO,
                REGISTROS_LIDOS,
                REGISTROS_INSERIDOS,
                REGISTROS_ATUALIZADOS,
                REGISTROS_REJEITADOS,
                STATUS_IMPORTACAO
            )
            VALUES
            (?, CURRENT_TIMESTAMP, ?, ?, ?, ?, ?, ?)
            """,
            [
                file.filename,
                user,
                registros_lidos,
                registros_inseridos,
                registros_atualizados,
                registros_rejeitados,
                status_importacao,
            ],
        )

        conn.commit()

        return {
            "success": True,
            "registros_lidos": registros_lidos,
            "registros_inseridos": registros_inseridos,
            "registros_atualizados": registros_atualizados,
            "registros_rejeitados": registros_rejeitados,
            "status_importacao": status_importacao,
            "erros": erros[:50],
        }

    except HTTPException:
        if conn:
            conn.rollback()
        raise

    except Exception as error:
        if conn:
            conn.rollback()
        raise HTTPException(
            status_code=500,
            detail=f"Erro ao importar novos entrantes: {str(error)}",
        )

    finally:
        if cursor:
            cursor.close()
        if conn:
            conn.close()


class EntradaUpdate(BaseModel):
    NOME_FANTASIA: Optional[str] = None

    LOGRADOURO: Optional[str] = None
    NUMERO_ENDERECO: Optional[str] = None
    BAIRRO: Optional[str] = None
    CEP: Optional[str] = None
    MUNICIPIO: Optional[str] = None
    UF: Optional[str] = None

    EMAIL_CONTATO: Optional[str] = None
    TELEFONE_CONTATO: Optional[str] = None

    INSCRICAO_MUNICIPAL: Optional[str] = None
    INSCRICAO_ESTADUAL: Optional[str] = None

    PROCESSO_SEI_ANATEL: Optional[str] = None

    NOME_RESPONSAVEL: Optional[str] = None
    CPF_RESPONSAVEL: Optional[str] = None
    RG_RESPONSAVEL: Optional[str] = None
    EMAIL_RESPONSAVEL: Optional[str] = None
    TELEFONE_RESPONSAVEL: Optional[str] = None

    POSSUI_GEOS: Optional[str] = None
    POSSUI_OS_GEOS: Optional[str] = None

    REDE_FIBRA: Optional[str] = None
    ATENDE_DIS_NOR_056: Optional[str] = None

    QTD_MUNICIPIOS: Optional[int] = None
    MUNICIPIOS_ATUACAO: Optional[str] = None
    QTD_POSTES: Optional[int] = None

    INFORMACOES_ADICIONAIS: Optional[str] = None

    CLASSIFICACAO: Optional[str] = None
    PRIORIDADE: Optional[str] = None
    POTENCIAL_RECEITA: Optional[str] = None
    OBSERVACOES: Optional[str] = None




@router.patch("/api/novos-entrantes/entrada/{id_entrada}")
async def atualizar_entrada(id_entrada: int, dados: EntradaUpdate):
    try:
        conn = main.get_connection()
        cursor = conn.cursor()

        cursor.execute("""
            SELECT STATUS_ENTRADA
            FROM CLB349328.PORTAL_COMPARTILHAMENTO_ENTRADA
            WHERE ID_ENTRADA = ?
        """, (id_entrada,))

        registro = cursor.fetchone()

        if not registro:
            raise HTTPException(
                status_code=404,
                detail="Entrante não encontrado"
            )

        status_atual = registro[0]

        campos = []
        valores = []

        for campo, valor in dados.dict().items():
            if valor is not None:
                campos.append(f'"{campo}" = ?')
                valores.append(valor)

        if not campos:
            return {"mensagem": "Nada para atualizar"}

        set_components = []
        set_components.extend(campos)

        # Somente altera para ANALISADO se ainda estiver NOVO
        if status_atual == "NOVO":
            set_components.append(
                "STATUS_ENTRADA = 'ANALISADO'"
            )

        set_components.append(
            "UPDATED_AT = CURRENT_TIMESTAMP"
        )

        sql = f"""
            UPDATE CLB349328.PORTAL_COMPARTILHAMENTO_ENTRADA
               SET {', '.join(set_components)}
             WHERE ID_ENTRADA = ?
        """

        valores.append(id_entrada)

        cursor.execute(sql, valores)

        if status_atual == "NOVO":
            _registrar_evento_entrada(cursor, id_entrada, "NOVO", "ANALISADO")

        conn.commit()

        return {
            "success": True,
            "id_entrada": id_entrada
        }

    except Exception as e:
        raise HTTPException(
            status_code=500,
            detail=str(e)
        )



@router.post(
    "/api/novos-entrantes/entrada/{id_entrada}/criar-provedor"
)
async def criar_provedor(id_entrada: int):

    try:

        conn = main.get_connection()
        cursor = conn.cursor()

        # Buscar Entrante
        cursor.execute("""
            SELECT
                RAZAO_SOCIAL,
                NOME_FANTASIA,
                CNPJ,
                NOME_RESPONSAVEL,
                EMAIL_CONTATO,
                TELEFONE_CONTATO,
                STATUS_ENTRADA
            FROM CLB349328.PORTAL_COMPARTILHAMENTO_ENTRADA
            WHERE ID_ENTRADA = ?
        """, (id_entrada,))

        entrada = cursor.fetchone()

        if not entrada:
            raise HTTPException(
                status_code=404,
                detail="Entrante não encontrado"
            )

        status_entrada = entrada[6]

        if status_entrada != "ANALISADO":
            if status_entrada in ("PROVEDOR_CRIADO", "PROCESSO_CRIADO"):
                detalhe = "Este entrante já possui provedor criado."
            elif status_entrada == "DESCARTADO":
                detalhe = "Este entrante foi descartado e não pode gerar provedor."
            else:
                detalhe = "Analise o entrante (salve os dados cadastrais) antes de criar o provedor."

            raise HTTPException(
                status_code=409,
                detail=detalhe
            )

        # Criar Provedor

        # Validar duplicidade de CNPJ
        cursor.execute("""
            SELECT 1
            FROM CLB349328.PORTAL_COMPARTILHAMENTO_PROVEDOR
            WHERE CNPJ = ?
        """, (entrada[2],))

        if cursor.fetchone():
            raise HTTPException(
                status_code=409,
                detail="Provedor com este CNPJ já existe"
            )

        cursor.execute("""
            INSERT INTO CLB349328.PORTAL_COMPARTILHAMENTO_PROVEDOR (
                CNPJ,
                RAZAO_SOCIAL,
                NOME_FANTASIA,
                RESPONSAVEL,
                EMAIL,
                TELEFONE,
                STATUS_CADASTRO
            )
            VALUES (
                ?, ?, ?, ?, ?, ?, ?
            )
        """, (
            entrada[2],
            entrada[0],
            entrada[1],
            entrada[3],
            entrada[4],
            entrada[5],
            "ATIVO"
        ))


        conn.commit()

        # Recuperar ID criado
        cursor.execute("""
            SELECT MAX(ID_PROVEDOR)
            FROM CLB349328.PORTAL_COMPARTILHAMENTO_PROVEDOR
        """)

        id_provedor = cursor.fetchone()[0]

        # Atualizar Entrante
        cursor.execute("""
            UPDATE CLB349328.PORTAL_COMPARTILHAMENTO_ENTRADA
               SET STATUS_ENTRADA = 'PROVEDOR_CRIADO',
                   UPDATED_AT = CURRENT_TIMESTAMP
             WHERE ID_ENTRADA = ?
        """, (id_entrada,))

        _registrar_evento_entrada(cursor, id_entrada, "ANALISADO", "PROVEDOR_CRIADO")

        conn.commit()

        return {
            "success": True,
            "id_provedor": id_provedor,
            "id_entrada": id_entrada,
            "mensagem": "Provedor criado com sucesso"
        }

    except HTTPException:
        raise
    except Exception as e:

        raise HTTPException(
            status_code=500,
            detail=str(e)
        )


@router.get("/api/provedores/existe/{cnpj}")
async def verificar_provedor_existente(cnpj: str):

    conn = main.get_connection()
    cursor = conn.cursor()

    cursor.execute("""
        SELECT
            ID_PROVEDOR,
            RAZAO_SOCIAL
        FROM CLB349328.PORTAL_COMPARTILHAMENTO_PROVEDOR
        WHERE CNPJ = ?
    """, (cnpj,))

    registro = cursor.fetchone()

    return {
        "existe": registro is not None,
        "id_provedor": registro[0] if registro else None,
        "razao_social": registro[1] if registro else None,
    }





