# -*- coding: utf-8 -*-
"""
Projetos de Compartilhamento de Infraestrutura.

Cobre, por enquanto, a criação manual de projeto associando a um
provedor/processo existente. O DDL canônico das tabelas está em
sql/PORTAL_COMPARTILHAMENTO_PROJETO.sql; aqui há um self-create de
segurança no mesmo espírito de outras partes do portal.

Endpoints consumidos por app/(app)/projetos/page.tsx +
components/projetos/novo-projeto-modal.tsx.
"""
from typing import Any, Optional, List
from datetime import datetime, date
import re

from fastapi import APIRouter, HTTPException, Path, Body
from decimal import Decimal

import main

router = APIRouter()

SCHEMA = "CLB349328"
TB_PROJETO = f"{SCHEMA}.PORTAL_COMPARTILHAMENTO_PROJETO"
TB_TIPO_DOC = f"{SCHEMA}.PORTAL_COMPARTILHAMENTO_PROJETO_TIPO_DOCUMENTO"
TB_DOC = f"{SCHEMA}.PORTAL_COMPARTILHAMENTO_PROJETO_DOCUMENTO"
TB_HIST = f"{SCHEMA}.PORTAL_COMPARTILHAMENTO_PROJETO_HISTORICO"
TB_PROVEDOR = f"{SCHEMA}.PORTAL_COMPARTILHAMENTO_PROVEDOR"
TB_PROCESSO = f"{SCHEMA}.PORTAL_COMPARTILHAMENTO_PROCESSO"
TB_ENTRADA = f"{SCHEMA}.PORTAL_COMPARTILHAMENTO_ENTRADA"

PRIORIDADES = {"BAIXA", "MEDIA", "ALTA", "URGENTE"}

# Catálogo padrão de documentos (espelha o seed do sql/ e do mock).
_SEED_TIPOS_DOC = [
    ("OFICIO_SOLICITACAO", "Ofício de solicitação de compartilhamento", "S", "pdf", 10),
    ("PLANILHA_POSTES", "Planilha de postes", "S", "xlsx,csv", 20),
    ("PROJETO_TECNICO", "Projeto técnico / memorial descritivo", "S", "pdf", 30),
    ("ART_TRT", "ART / TRT do responsável técnico", "S", "pdf", 40),
    ("LICENCA_ANATEL", "Licença / outorga ANATEL", "S", "pdf", 50),
    ("CONTRATO_SOCIAL", "Contrato social / CNPJ", "S", "pdf", 60),
    ("KML_TRACADO", "Arquivo KML/KMZ do traçado", "N", "kml,kmz", 70),
]


def _json_value(value: Any) -> Any:
    if isinstance(value, Decimal):
        return float(value)
    if isinstance(value, (datetime, date)):
        return value.isoformat()
    return value


def _linhas(cursor) -> List[dict]:
    colunas = [c[0] for c in cursor.description]
    return [
        {colunas[i]: _json_value(v) for i, v in enumerate(row)}
        for row in cursor.fetchall()
    ]


def _so_digitos(valor: Any) -> str:
    return re.sub(r"\D", "", str(valor or ""))


def _garantir_tabelas_projeto(cursor) -> None:
    """Cria as tabelas de Projetos na primeira vez (mesmo padrão self-create
    usado no resto do portal). O DDL de referência, com índices e a view de
    jornada, está em sql/PORTAL_COMPARTILHAMENTO_PROJETO.sql."""
    try:
        cursor.execute(f"SELECT COUNT(*) FROM {TB_PROJETO}")
        cursor.fetchone()
        precisa_criar = False
    except Exception:
        precisa_criar = True

    if precisa_criar:
        cursor.execute(
            f"""
            CREATE COLUMN TABLE {TB_PROJETO}
            (
                ID_PROJETO INTEGER CS_INT GENERATED BY DEFAULT AS IDENTITY,
                NUMERO_PROJETO NVARCHAR(40) NOT NULL,
                TITULO NVARCHAR(200),
                CHAVE_CONEXAO NVARCHAR(14) NOT NULL,
                ID_PROVEDOR INTEGER,
                ID_PROCESSO INTEGER,
                NUMERO_PROTOCOLO NVARCHAR(30),
                CNPJ NVARCHAR(20) NOT NULL,
                RAZAO_SOCIAL NVARCHAR(200) NOT NULL,
                NOME_FANTASIA NVARCHAR(200),
                MUNICIPIO NVARCHAR(120),
                UF NVARCHAR(2),
                REGIONAL NVARCHAR(60),
                QTD_POSTES_INFORMADA INTEGER DEFAULT 0,
                QTD_POSTES_RECEBIDA INTEGER DEFAULT 0,
                QTD_POSTES_VALIDADA INTEGER DEFAULT 0,
                STATUS_PROJETO NVARCHAR(20) DEFAULT 'RECEBIDO',
                PRIORIDADE NVARCHAR(10) DEFAULT 'MEDIA',
                RESPONSAVEL_ANALISE NVARCHAR(100),
                PRAZO_ANALISE DATE,
                DATA_CONCLUSAO LONGDATE CS_LONGDATE,
                CANAL_ORIGEM NVARCHAR(20) DEFAULT 'EMAIL',
                SUBMETIDO_POR NVARCHAR(100),
                EMAIL_REMETENTE NVARCHAR(200),
                DATA_RECEBIMENTO LONGDATE CS_LONGDATE,
                DOCS_OBRIGATORIOS INTEGER DEFAULT 0,
                DOCS_RECEBIDOS INTEGER DEFAULT 0,
                DOCS_VALIDADOS INTEGER DEFAULT 0,
                DOCUMENTACAO_OK NVARCHAR(1) DEFAULT 'N',
                OBSERVACOES NVARCHAR(4000),
                CREATED_AT LONGDATE CS_LONGDATE,
                CREATED_BY NVARCHAR(100),
                UPDATED_AT LONGDATE CS_LONGDATE,
                UPDATED_BY NVARCHAR(100),
                ATIVO NVARCHAR(1) DEFAULT 'S',
                PRIMARY KEY (ID_PROJETO)
            )
            UNLOAD PRIORITY 5 AUTO MERGE
            """
        )

    try:
        cursor.execute(f"SELECT COUNT(*) FROM {TB_TIPO_DOC}")
        total_catalogo = cursor.fetchone()[0] or 0
    except Exception:
        cursor.execute(
            f"""
            CREATE COLUMN TABLE {TB_TIPO_DOC}
            (
                ID_TIPO_DOCUMENTO INTEGER CS_INT GENERATED BY DEFAULT AS IDENTITY,
                CODIGO NVARCHAR(40) NOT NULL,
                NOME NVARCHAR(150) NOT NULL,
                DESCRICAO NVARCHAR(500),
                OBRIGATORIO NVARCHAR(1) DEFAULT 'S',
                EXTENSOES_ACEITAS NVARCHAR(120),
                ORDEM INTEGER DEFAULT 0,
                ATIVO NVARCHAR(1) DEFAULT 'S',
                CREATED_AT LONGDATE CS_LONGDATE,
                UPDATED_AT LONGDATE CS_LONGDATE,
                PRIMARY KEY (ID_TIPO_DOCUMENTO)
            )
            UNLOAD PRIORITY 5 AUTO MERGE
            """
        )
        total_catalogo = 0

    if total_catalogo == 0:
        for codigo, nome, obrig, ext, ordem in _SEED_TIPOS_DOC:
            cursor.execute(
                f"""
                INSERT INTO {TB_TIPO_DOC}
                (CODIGO, NOME, OBRIGATORIO, EXTENSOES_ACEITAS, ORDEM, ATIVO, CREATED_AT)
                VALUES (?, ?, ?, ?, ?, 'S', CURRENT_UTCTIMESTAMP)
                """,
                [codigo, nome, obrig, ext, ordem],
            )

    try:
        cursor.execute(f"SELECT COUNT(*) FROM {TB_DOC}")
        cursor.fetchone()
    except Exception:
        cursor.execute(
            f"""
            CREATE COLUMN TABLE {TB_DOC}
            (
                ID_PROJETO_DOCUMENTO INTEGER CS_INT GENERATED BY DEFAULT AS IDENTITY,
                ID_PROJETO INTEGER NOT NULL,
                ID_SUBMISSAO INTEGER,
                CODIGO_TIPO NVARCHAR(40),
                TIPO_DOCUMENTO NVARCHAR(150),
                OBRIGATORIO NVARCHAR(1) DEFAULT 'N',
                NOME_ARQUIVO NVARCHAR(255),
                TIPO_ARQUIVO NVARCHAR(120),
                CAMINHO_ARQUIVO NVARCHAR(1000),
                TAMANHO_BYTES BIGINT,
                HASH_ARQUIVO NVARCHAR(64),
                STATUS_DOCUMENTO NVARCHAR(20) DEFAULT 'PENDENTE',
                MOTIVO_REJEICAO NVARCHAR(500),
                RECEBIDO_VIA NVARCHAR(20) DEFAULT 'EMAIL',
                EMAIL_REMETENTE NVARCHAR(200),
                DATA_RECEBIMENTO LONGDATE CS_LONGDATE,
                VALIDADO_POR NVARCHAR(100),
                DATA_VALIDACAO LONGDATE CS_LONGDATE,
                OBSERVACAO NVARCHAR(1000),
                CREATED_AT LONGDATE CS_LONGDATE,
                ATIVO NVARCHAR(1) DEFAULT 'S',
                PRIMARY KEY (ID_PROJETO_DOCUMENTO)
            )
            UNLOAD PRIORITY 5 AUTO MERGE
            """
        )

    try:
        cursor.execute(f"SELECT COUNT(*) FROM {TB_HIST}")
        cursor.fetchone()
    except Exception:
        cursor.execute(
            f"""
            CREATE COLUMN TABLE {TB_HIST}
            (
                ID_HISTORICO INTEGER CS_INT GENERATED BY DEFAULT AS IDENTITY,
                ID_PROJETO INTEGER NOT NULL,
                TIPO_EVENTO NVARCHAR(30),
                STATUS_ANTERIOR NVARCHAR(20),
                STATUS_NOVO NVARCHAR(20),
                DESCRICAO NVARCHAR(1000),
                USUARIO NVARCHAR(100),
                DATA_EVENTO LONGDATE CS_LONGDATE,
                PRIMARY KEY (ID_HISTORICO)
            )
            UNLOAD PRIORITY 5 AUTO MERGE
            """
        )


@router.get("/api/projetos/opcoes-vinculo", response_model=List[dict])
def opcoes_vinculo_projeto():
    """Provedores existentes + seus processos, para o formulário de novo projeto."""
    conn = None
    cursor = None
    try:
        conn = main.get_connection()
        cursor = conn.cursor()

        cursor.execute(
            f"""
            SELECT
                PR.ID_PROVEDOR,
                PR.RAZAO_SOCIAL,
                PR.NOME_FANTASIA,
                PR.CNPJ,
                PR.STATUS_CADASTRO,
                (
                    SELECT MAX(E.MUNICIPIO)
                    FROM {TB_ENTRADA} E
                    WHERE E.CNPJ = PR.CNPJ
                ) AS MUNICIPIO
            FROM {TB_PROVEDOR} PR
            ORDER BY PR.RAZAO_SOCIAL ASC
            """
        )
        provedores = _linhas(cursor)

        cursor.execute(
            f"""
            SELECT ID_PROVEDOR, ID_PROCESSO, NUMERO_PROTOCOLO, STATUS_ATUAL, ETAPA_ATUAL
            FROM {TB_PROCESSO}
            ORDER BY ID_PROCESSO ASC
            """
        )
        processos_por_provedor: dict = {}
        for proc in _linhas(cursor):
            processos_por_provedor.setdefault(proc["ID_PROVEDOR"], []).append(
                {
                    "ID_PROCESSO": proc["ID_PROCESSO"],
                    "NUMERO_PROTOCOLO": proc["NUMERO_PROTOCOLO"],
                    "STATUS_ATUAL": proc["STATUS_ATUAL"],
                    "ETAPA_ATUAL": proc["ETAPA_ATUAL"],
                }
            )

        return [
            {
                "ID_PROVEDOR": p["ID_PROVEDOR"],
                "RAZAO_SOCIAL": p["RAZAO_SOCIAL"],
                "NOME_FANTASIA": p["NOME_FANTASIA"],
                "CNPJ": p["CNPJ"],
                "MUNICIPIO": p.get("MUNICIPIO"),
                "UF": None,
                "STATUS_CADASTRO": p["STATUS_CADASTRO"],
                "processos": processos_por_provedor.get(p["ID_PROVEDOR"], []),
            }
            for p in provedores
        ]
    finally:
        if cursor:
            cursor.close()
        if conn:
            conn.close()


@router.post("/api/projetos", response_model=dict)
def criar_projeto_manual(payload: dict = Body(...)):
    """Cria um projeto manualmente e o associa a um provedor (e, opcionalmente,
    a um processo) existentes. O projeto entra como RECEBIDO, canal MANUAL,
    com o checklist de documentos obrigatórios todo PENDENTE."""
    id_provedor = payload.get("id_provedor")
    id_processo = payload.get("id_processo")
    prioridade = str(payload.get("prioridade") or "MEDIA").strip().upper()
    if prioridade not in PRIORIDADES:
        prioridade = "MEDIA"

    def _texto(valor: Any) -> Optional[str]:
        t = str(valor).strip() if valor is not None else ""
        return t or None

    try:
        qtd_postes = int(payload.get("qtd_postes_informada") or 0)
    except (TypeError, ValueError):
        qtd_postes = 0

    conn = None
    cursor = None
    try:
        conn = main.get_connection()
        cursor = conn.cursor()
        _garantir_tabelas_projeto(cursor)

        provedor = None
        if id_provedor is not None:
            cursor.execute(
                f"SELECT ID_PROVEDOR, CNPJ, RAZAO_SOCIAL, NOME_FANTASIA FROM {TB_PROVEDOR} WHERE ID_PROVEDOR = ?",
                [int(id_provedor)],
            )
            row = cursor.fetchone()
            if not row:
                raise HTTPException(status_code=404, detail="Provedor não encontrado")
            provedor = {"ID_PROVEDOR": row[0], "CNPJ": row[1], "RAZAO_SOCIAL": row[2], "NOME_FANTASIA": row[3]}

        processo = None
        if id_processo is not None:
            cursor.execute(
                f"SELECT ID_PROCESSO, ID_PROVEDOR, NUMERO_PROTOCOLO FROM {TB_PROCESSO} WHERE ID_PROCESSO = ?",
                [int(id_processo)],
            )
            row = cursor.fetchone()
            if not row:
                raise HTTPException(status_code=404, detail="Processo não encontrado")
            processo = {"ID_PROCESSO": row[0], "ID_PROVEDOR": row[1], "NUMERO_PROTOCOLO": row[2]}
            if provedor and processo["ID_PROVEDOR"] != provedor["ID_PROVEDOR"]:
                raise HTTPException(
                    status_code=400,
                    detail="O processo informado não pertence ao provedor selecionado",
                )

        cnpj = _texto(payload.get("cnpj")) or (provedor["CNPJ"] if provedor else None)
        razao = _texto(payload.get("razao_social")) or (provedor["RAZAO_SOCIAL"] if provedor else None)
        if not provedor and not razao:
            raise HTTPException(status_code=400, detail="Selecione um provedor ou informe a razão social")

        fantasia = _texto(payload.get("nome_fantasia")) or (provedor["NOME_FANTASIA"] if provedor else None)
        municipio = _texto(payload.get("municipio")) or "Salvador"
        uf = (_texto(payload.get("uf")) or "BA")[:2].upper()
        usuario = _texto(payload.get("usuario")) or "CLB349328"

        # Número do projeto: PRJ-<ano>-<sequencial global, 6 dígitos>.
        cursor.execute(f"SELECT COUNT(*) FROM {TB_PROJETO}")
        seq = (cursor.fetchone()[0] or 0) + 1
        numero_projeto = f"PRJ-{datetime.utcnow().year}-{seq:06d}"
        titulo = _texto(payload.get("titulo")) or f"Compartilhamento {fantasia or razao} - {municipio}"

        cursor.execute(
            f"""
            INSERT INTO {TB_PROJETO}
            (
                NUMERO_PROJETO, TITULO, CHAVE_CONEXAO, ID_PROVEDOR, ID_PROCESSO,
                NUMERO_PROTOCOLO, CNPJ, RAZAO_SOCIAL, NOME_FANTASIA, MUNICIPIO, UF,
                REGIONAL, QTD_POSTES_INFORMADA, QTD_POSTES_RECEBIDA, QTD_POSTES_VALIDADA,
                STATUS_PROJETO, PRIORIDADE, CANAL_ORIGEM, SUBMETIDO_POR, DATA_RECEBIMENTO,
                DOCS_OBRIGATORIOS, DOCS_RECEBIDOS, DOCS_VALIDADOS, DOCUMENTACAO_OK,
                CREATED_AT, CREATED_BY, UPDATED_AT, UPDATED_BY, ATIVO
            )
            VALUES
            (
                ?, ?, ?, ?, ?,
                ?, ?, ?, ?, ?, ?,
                ?, ?, 0, 0,
                'RECEBIDO', ?, 'MANUAL', ?, CURRENT_UTCTIMESTAMP,
                0, 0, 0, 'N',
                CURRENT_UTCTIMESTAMP, ?, CURRENT_UTCTIMESTAMP, ?, 'S'
            )
            """,
            [
                numero_projeto, titulo, _so_digitos(cnpj),
                provedor["ID_PROVEDOR"] if provedor else None,
                processo["ID_PROCESSO"] if processo else None,
                processo["NUMERO_PROTOCOLO"] if processo else None,
                cnpj, razao, fantasia, municipio, uf,
                "Metropolitana", qtd_postes,
                prioridade, usuario, usuario, usuario,
            ],
        )
        cursor.execute("SELECT CURRENT_IDENTITY_VALUE() FROM DUMMY")
        id_projeto = int(cursor.fetchone()[0])

        # Checklist de documentos: 1 linha por tipo ativo do catálogo, PENDENTE.
        cursor.execute(
            f"""
            INSERT INTO {TB_DOC}
            (
                ID_PROJETO, CODIGO_TIPO, TIPO_DOCUMENTO, OBRIGATORIO,
                STATUS_DOCUMENTO, RECEBIDO_VIA, CREATED_AT, ATIVO
            )
            SELECT ?, CODIGO, NOME, OBRIGATORIO, 'PENDENTE', 'MANUAL', CURRENT_UTCTIMESTAMP, 'S'
            FROM {TB_TIPO_DOC}
            WHERE ATIVO = 'S'
            """,
            [id_projeto],
        )

        cursor.execute(
            f"SELECT COUNT(*) FROM {TB_DOC} WHERE ID_PROJETO = ? AND OBRIGATORIO = 'S' AND ATIVO = 'S'",
            [id_projeto],
        )
        docs_obrigatorios = cursor.fetchone()[0] or 0
        cursor.execute(
            f"UPDATE {TB_PROJETO} SET DOCS_OBRIGATORIOS = ? WHERE ID_PROJETO = ?",
            [docs_obrigatorios, id_projeto],
        )

        descricao_hist = (
            f"Projeto criado manualmente e vinculado ao processo {processo['NUMERO_PROTOCOLO']}."
            if processo
            else f"Projeto criado manualmente e vinculado ao provedor {razao}."
            if provedor
            else "Projeto criado manualmente."
        )
        cursor.execute(
            f"""
            INSERT INTO {TB_HIST}
            (ID_PROJETO, TIPO_EVENTO, STATUS_ANTERIOR, STATUS_NOVO, DESCRICAO, USUARIO, DATA_EVENTO)
            VALUES (?, 'RECEBIMENTO', NULL, 'RECEBIDO', ?, ?, CURRENT_UTCTIMESTAMP)
            """,
            [id_projeto, descricao_hist, usuario],
        )

        conn.commit()
        return {
            "success": True,
            "id_projeto": id_projeto,
            "numero_projeto": numero_projeto,
            "vinculo_resolvido": bool(provedor),
        }
    except HTTPException:
        if conn:
            conn.rollback()
        raise
    except Exception as error:
        if conn:
            conn.rollback()
        raise HTTPException(status_code=500, detail=f"Erro ao criar o projeto: {error}")
    finally:
        if cursor:
            cursor.close()
        if conn:
            conn.close()
