from fastapi import APIRouter, HTTPException, Path, Request
from typing import List, Optional
from pydantic import BaseModel

import main
from routers.entrantes import _criar_processo_para_provedor
from routers.processos import _processos_rows_to_dicts, _processos_json_value
from routers.auth import _auth_extrair_bearer_token, _auth_validar_token
from routers.postes import inserir_acao_poste, TB_OCUPACAO as _TB_OCUPACAO, TB_OPERADORA as _TB_OPERADORA, TB_POSTE as _TB_POSTE

router = APIRouter()

SCHEMA_SOLICITACAO = "CLB349328"
TB_PROVEDOR_SOLICITACAO = f"{SCHEMA_SOLICITACAO}.PORTAL_COMPARTILHAMENTO_PROVEDOR"
TB_PROCESSO_SOLICITACAO = f"{SCHEMA_SOLICITACAO}.PORTAL_COMPARTILHAMENTO_PROCESSO"
TB_SOLICITACAO_ACAO = f"{SCHEMA_SOLICITACAO}.PORTAL_COMPARTILHAMENTO_SOLICITACAO_ACAO"


def _somente_digitos_sql(coluna: str) -> str:
    """Normaliza um CNPJ pra comparação, tirando pontuação - o CNPJ pode
    estar salvo formatado diferente entre PROVEDOR e OPERADORA (tabelas
    independentes historicamente, ver nota em listar_postes_do_provedor)."""
    return f"REPLACE(REPLACE(REPLACE({coluna}, '.', ''), '/', ''), '-', '')"

# =====================================================
# Contratos: provedores que já concluíram a jornada + solicitação de ação a
# times de Técnico, Negociação e Comercial. Ver
# sql_nova_tabela_solicitacao_acao.txt para o schema da tabela nova - ela é
# criada sozinha na primeira chamada (mesmo padrão de TB_ACAO em postes.py e
# da tabela de OTP em auth.py), não precisa rodar migração manual.
# =====================================================

CATALOGO_TIPOS_ACAO = {
    "REMOCAO": {"label": "Solicitar remoção", "time": "TECNICO"},
    "NOTIFICACAO": {"label": "Encaminhar notificação ao provedor", "time": "COMERCIAL"},
    "COBRANCA": {"label": "Solicitar cobrança", "time": "NEGOCIACAO"},
    "DESFAZER_CONTRATO": {"label": "Solicitar desfazimento do contrato", "time": "COMERCIAL"},
    "OUTRO": {"label": "Outra solicitação", "time": "COMERCIAL"},
}
TIMES_RESPONSAVEL_VALIDOS = {"TECNICO", "NEGOCIACAO", "COMERCIAL"}
STATUS_SOLICITACAO_VALIDOS = {"ABERTA", "EM_ANDAMENTO", "CONCLUIDA", "CANCELADA"}


def _solicitacoes_garantir_tabela(cursor) -> None:
    try:
        cursor.execute(f"SELECT COUNT(*) FROM {TB_SOLICITACAO_ACAO}")
        cursor.fetchone()
        return
    except Exception:
        pass

    cursor.execute(f"""
        CREATE COLUMN TABLE {TB_SOLICITACAO_ACAO}
        (
            "ID_SOLICITACAO" INTEGER CS_INT GENERATED BY DEFAULT AS IDENTITY,
            "ID_PROVEDOR" INTEGER NOT NULL,
            "ID_PROCESSO" INTEGER,
            "ID_ACAO_POSTE" INTEGER,
            "TIPO_ACAO" NVARCHAR(30) NOT NULL,
            "TIME_RESPONSAVEL" NVARCHAR(20) NOT NULL,
            "DESCRICAO" NVARCHAR(2000),
            "PRIORIDADE" NVARCHAR(10) DEFAULT 'MEDIA',
            "STATUS" NVARCHAR(20) DEFAULT 'ABERTA',
            "SOLICITADO_POR" NVARCHAR(100),
            "DATA_SOLICITACAO" LONGDATE CS_LONGDATE,
            "RESPONSAVEL_EXECUCAO" NVARCHAR(100),
            "DATA_CONCLUSAO" LONGDATE CS_LONGDATE,
            "OBSERVACAO_CONCLUSAO" NVARCHAR(2000),
            "CREATED_AT" LONGDATE CS_LONGDATE,
            "UPDATED_AT" LONGDATE CS_LONGDATE,
            PRIMARY KEY ("ID_SOLICITACAO")
        )
        UNLOAD PRIORITY 5 AUTO MERGE
    """)


class SolicitacaoAcaoCreate(BaseModel):
    tipo_acao: str
    descricao: Optional[str] = None
    prioridade: Optional[str] = "MEDIA"
    id_processo: Optional[int] = None
    time_responsavel: Optional[str] = None
    barramentos: Optional[List[str]] = None


class SolicitacaoAcaoUpdate(BaseModel):
    status: str
    observacao_conclusao: Optional[str] = None
    responsavel_execucao: Optional[str] = None


@router.get("/api/provedores", response_model=List[dict])
def listar_provedores():
    """Provedores que já percorreram toda a jornada (têm ao menos um
    processo concluído) - base da tela Comercial > Contratos."""
    conn = None
    cursor = None
    try:
        conn = main.get_connection()
        cursor = conn.cursor()

        cursor.execute(f"""
            SELECT
                P.ID_PROVEDOR, P.CNPJ, P.RAZAO_SOCIAL, P.NOME_FANTASIA,
                P.RESPONSAVEL, P.EMAIL, P.TELEFONE, P.STATUS_CADASTRO,
                COUNT(PR.ID_PROCESSO) AS TOTAL_PROCESSOS,
                MAX(PR.DT_CONCLUSAO) AS ULTIMA_CONCLUSAO
            FROM {TB_PROVEDOR_SOLICITACAO} P
            INNER JOIN {TB_PROCESSO_SOLICITACAO} PR
                ON PR.ID_PROVEDOR = P.ID_PROVEDOR AND PR.STATUS_ATUAL = 'CONCLUIDO'
            GROUP BY P.ID_PROVEDOR, P.CNPJ, P.RAZAO_SOCIAL, P.NOME_FANTASIA,
                     P.RESPONSAVEL, P.EMAIL, P.TELEFONE, P.STATUS_CADASTRO
            ORDER BY P.RAZAO_SOCIAL ASC
        """)
        colunas = [c[0] for c in cursor.description]
        return [
            {colunas[i]: _processos_json_value(v) for i, v in enumerate(row)}
            for row in cursor.fetchall()
        ]
    except Exception as e:
        raise HTTPException(status_code=500, detail=str(e))
    finally:
        if cursor:
            cursor.close()
        if conn:
            conn.close()


@router.get("/api/provedores/{id}/postes", response_model=List[dict])
def listar_postes_do_provedor(id: int = Path(..., alias="id")):
    """Postes/ocupações deste provedor no Mapa de Postes - usado pelo
    modal de 'Solicitar Ação' quando o tipo é Remoção, pra deixar escolher
    quais postes são o alvo.

    PROVEDOR (jornada comercial) e OPERADORA (mapa de postes) são tabelas
    independentes historicamente; aqui elas são ligadas pelo CNPJ, tolerando
    diferença de formatação (com/sem pontuação) entre as duas."""
    conn = None
    cursor = None
    try:
        conn = main.get_connection()
        cursor = conn.cursor()

        cursor.execute(f"SELECT CNPJ FROM {TB_PROVEDOR_SOLICITACAO} WHERE ID_PROVEDOR = ?", [id])
        linha = cursor.fetchone()
        if not linha:
            raise HTTPException(status_code=404, detail="Provedor não encontrado")
        cnpj = linha[0]

        cursor.execute(
            f"""
            SELECT O."BARRAMENTO", O."BOARD_NAME", P."X", P."Y"
            FROM {_TB_OCUPACAO} O
            INNER JOIN {_TB_OPERADORA} OP ON {_somente_digitos_sql('OP."CNPJ"')} = {_somente_digitos_sql('?')}
            LEFT JOIN {_TB_POSTE} P ON P."BARRAMENTO" = O."BARRAMENTO"
            WHERE O."BARRAMENTO" IS NOT NULL
            ORDER BY O."BOARD_NAME"
            """,
            [cnpj],
        )
        colunas = [c[0] for c in cursor.description]
        return [
            {colunas[i]: _processos_json_value(v) for i, v in enumerate(row)}
            for row in cursor.fetchall()
        ]
    except HTTPException:
        raise
    except Exception as e:
        raise HTTPException(status_code=500, detail=str(e))
    finally:
        if cursor:
            cursor.close()
        if conn:
            conn.close()


@router.get("/api/provedores/{id}/acoes", response_model=List[dict])
def listar_solicitacoes_acao(id: int = Path(..., alias="id")):
    conn = None
    cursor = None
    try:
        conn = main.get_connection()
        cursor = conn.cursor()
        _solicitacoes_garantir_tabela(cursor)

        cursor.execute(f"SELECT COUNT(*) FROM {TB_PROVEDOR_SOLICITACAO} WHERE ID_PROVEDOR = ?", [id])
        if not cursor.fetchone()[0]:
            raise HTTPException(status_code=404, detail="Provedor não encontrado")

        cursor.execute(f"""
            SELECT * FROM {TB_SOLICITACAO_ACAO}
            WHERE ID_PROVEDOR = ?
            ORDER BY DATA_SOLICITACAO DESC
        """, [id])
        colunas = [c[0] for c in cursor.description]
        return [
            {colunas[i]: _processos_json_value(v) for i, v in enumerate(row)}
            for row in cursor.fetchall()
        ]
    except HTTPException:
        raise
    except Exception as e:
        raise HTTPException(status_code=500, detail=str(e))
    finally:
        if cursor:
            cursor.close()
        if conn:
            conn.close()


@router.post("/api/provedores/{id}/acoes", response_model=dict)
def criar_solicitacao_acao(dados: SolicitacaoAcaoCreate, id: int = Path(..., alias="id"), request: Request = None):
    catalogo = CATALOGO_TIPOS_ACAO.get(dados.tipo_acao)
    if not catalogo:
        raise HTTPException(status_code=400, detail=f"tipo_acao deve ser um de: {', '.join(sorted(CATALOGO_TIPOS_ACAO))}")

    time_responsavel = dados.time_responsavel or catalogo["time"]
    if time_responsavel not in TIMES_RESPONSAVEL_VALIDOS:
        raise HTTPException(status_code=400, detail=f"time_responsavel deve ser um de: {', '.join(sorted(TIMES_RESPONSAVEL_VALIDOS))}")

    user = _usuario_do_request(request)
    conn = None
    cursor = None
    try:
        conn = main.get_connection()
        cursor = conn.cursor()
        _solicitacoes_garantir_tabela(cursor)

        cursor.execute(f"SELECT RAZAO_SOCIAL FROM {TB_PROVEDOR_SOLICITACAO} WHERE ID_PROVEDOR = ?", [id])
        linha_provedor = cursor.fetchone()
        if not linha_provedor:
            raise HTTPException(status_code=404, detail="Provedor não encontrado")

        # Remoção pode nascer já vinculada a postes reais do Mapa de Postes -
        # mesma ação (TB_ACAO), visível pro time técnico nos dois lugares.
        id_acao_poste = None
        if dados.tipo_acao == "REMOCAO" and dados.barramentos:
            id_acao_poste = inserir_acao_poste(
                cursor,
                tipo="REMOCAO",
                titulo=f"Remoção - {linha_provedor[0]}",
                responsavel=None,
                prazo=None,
                barramentos=dados.barramentos,
                observacao=dados.descricao,
                criado_por=user,
            )

        cursor.execute(
            f"""
            INSERT INTO {TB_SOLICITACAO_ACAO}
                (ID_PROVEDOR, ID_PROCESSO, ID_ACAO_POSTE, TIPO_ACAO, TIME_RESPONSAVEL, DESCRICAO, PRIORIDADE, STATUS, SOLICITADO_POR, DATA_SOLICITACAO, CREATED_AT, UPDATED_AT)
            VALUES (?,?,?,?,?,?,?,'ABERTA',?,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP)
            """,
            [id, dados.id_processo, id_acao_poste, dados.tipo_acao, time_responsavel, dados.descricao, dados.prioridade or "MEDIA", user],
        )

        cursor.execute(f"SELECT MAX(ID_SOLICITACAO) FROM {TB_SOLICITACAO_ACAO}")
        id_solicitacao = cursor.fetchone()[0]
        conn.commit()

        return {
            "success": True,
            "id_solicitacao": id_solicitacao,
            "id_provedor": id,
            "time_responsavel": time_responsavel,
            "id_acao_poste": id_acao_poste,
            "mensagem": "Solicitação registrada com sucesso.",
        }
    except HTTPException:
        if conn:
            conn.rollback()
        raise
    except Exception as e:
        if conn:
            conn.rollback()
        raise HTTPException(status_code=500, detail=str(e))
    finally:
        if cursor:
            cursor.close()
        if conn:
            conn.close()


@router.patch("/api/provedores/{id}/acoes/{id_solicitacao}", response_model=dict)
def atualizar_solicitacao_acao(
    dados: SolicitacaoAcaoUpdate,
    id: int = Path(..., alias="id"),
    id_solicitacao: int = Path(...),
    request: Request = None,
):
    if dados.status not in STATUS_SOLICITACAO_VALIDOS:
        raise HTTPException(status_code=400, detail=f"status deve ser um de: {', '.join(sorted(STATUS_SOLICITACAO_VALIDOS))}")

    user = _usuario_do_request(request)
    conn = None
    cursor = None
    try:
        conn = main.get_connection()
        cursor = conn.cursor()
        _solicitacoes_garantir_tabela(cursor)

        cursor.execute(
            f"SELECT ID_SOLICITACAO FROM {TB_SOLICITACAO_ACAO} WHERE ID_SOLICITACAO = ? AND ID_PROVEDOR = ?",
            [id_solicitacao, id],
        )
        if not cursor.fetchone():
            raise HTTPException(status_code=404, detail="Solicitação não encontrada")

        concluido = 1 if dados.status in ("CONCLUIDA", "CANCELADA") else 0
        cursor.execute(
            f"""
            UPDATE {TB_SOLICITACAO_ACAO}
               SET STATUS = ?,
                   OBSERVACAO_CONCLUSAO = COALESCE(?, OBSERVACAO_CONCLUSAO),
                   RESPONSAVEL_EXECUCAO = COALESCE(?, RESPONSAVEL_EXECUCAO),
                   DATA_CONCLUSAO = CASE WHEN ? = 1 THEN CURRENT_TIMESTAMP ELSE DATA_CONCLUSAO END,
                   UPDATED_AT = CURRENT_TIMESTAMP
             WHERE ID_SOLICITACAO = ?
            """,
            [dados.status, dados.observacao_conclusao, dados.responsavel_execucao or user, concluido, id_solicitacao],
        )
        conn.commit()

        return {"success": True, "id_solicitacao": id_solicitacao, "status": dados.status}
    except HTTPException:
        if conn:
            conn.rollback()
        raise
    except Exception as e:
        if conn:
            conn.rollback()
        raise HTTPException(status_code=500, detail=str(e))
    finally:
        if cursor:
            cursor.close()
        if conn:
            conn.close()


def _usuario_do_request(request: Request) -> str:
    """Tenta identificar o usuário real pelo token Bearer. Best-effort - os
    endpoints de provedor não exigem autenticação hoje (mesmo padrão já usado
    em routers/processos.py)."""
    try:
        token = _auth_extrair_bearer_token(request)
        payload = _auth_validar_token(token)
        return payload.get("login") or payload.get("email") or "CLB349328"
    except Exception:
        return "CLB349328"


@router.get("/api/provedores/{id}", response_model=dict)
def obter_provedor(id: int = Path(..., alias="id")):
    """Perfil do provedor: dados cadastrais + entrada original + todos os
    processos (um provedor pode ter mais de um PN/processo ao longo do tempo)."""
    conn = None
    cursor = None
    try:
        conn = main.get_connection()
        cursor = conn.cursor()

        cursor.execute(
            """
            SELECT ID_PROVEDOR, CNPJ, RAZAO_SOCIAL, NOME_FANTASIA, RESPONSAVEL, EMAIL, TELEFONE, STATUS_CADASTRO
            FROM CLB349328.PORTAL_COMPARTILHAMENTO_PROVEDOR
            WHERE ID_PROVEDOR = ?
            """,
            [id],
        )
        row = cursor.fetchone()
        if not row:
            raise HTTPException(status_code=404, detail="Provedor não encontrado")
        colunas_provedor = [c[0] for c in cursor.description]
        provedor = {colunas_provedor[i]: _processos_json_value(v) for i, v in enumerate(row)}

        cursor.execute(
            """
            SELECT ID_ENTRADA, DATA_RECEBIMENTO, STATUS_ENTRADA, MUNICIPIO
            FROM CLB349328.PORTAL_COMPARTILHAMENTO_ENTRADA
            WHERE CNPJ = ?
            ORDER BY DATA_RECEBIMENTO DESC
            LIMIT 1
            """,
            [provedor["CNPJ"]],
        )
        entrada_row = cursor.fetchone()
        entrada = None
        if entrada_row:
            colunas_entrada = [c[0] for c in cursor.description]
            entrada = {colunas_entrada[i]: _processos_json_value(v) for i, v in enumerate(entrada_row)}

        cursor.execute(
            """
            SELECT
                P.ID_PROCESSO,
                P.NUMERO_PROTOCOLO,
                P.TIPO_PROCESSO,
                P.STATUS_ATUAL,
                P.ETAPA_ATUAL,
                E.NOME_ETAPA AS NOME_ETAPA_ATUAL,
                P.DT_ABERTURA,
                P.DT_PREVISAO_CONCLUSAO,
                P.DT_CONCLUSAO
            FROM CLB349328.PORTAL_COMPARTILHAMENTO_PROCESSO P
            LEFT JOIN CLB349328.PORTAL_COMPARTILHAMENTO_ETAPA E
                ON E.ID_ETAPA = P.ETAPA_ATUAL
            WHERE P.ID_PROVEDOR = ?
            ORDER BY P.DT_ABERTURA DESC, P.ID_PROCESSO DESC
            """,
            [id],
        )
        processos = _processos_rows_to_dicts(cursor, cursor.fetchall())

        return {
            "provedor": provedor,
            "entrada": entrada,
            "processos": processos,
        }

    except HTTPException:
        raise
    except Exception as e:
        raise HTTPException(status_code=500, detail=str(e))
    finally:
        if cursor:
            cursor.close()
        if conn:
            conn.close()


@router.get("/api/provedores/{id}/timeline", response_model=List[dict])
def obter_timeline_provedor(id: int = Path(..., alias="id")):
    """Linha do tempo unificada do provedor: eventos da entrada original +
    jornada e contatos de TODOS os processos dele, ordenados por data."""
    conn = None
    cursor = None
    try:
        conn = main.get_connection()
        cursor = conn.cursor()

        cursor.execute(
            "SELECT CNPJ FROM CLB349328.PORTAL_COMPARTILHAMENTO_PROVEDOR WHERE ID_PROVEDOR = ?",
            [id],
        )
        row = cursor.fetchone()
        if not row:
            raise HTTPException(status_code=404, detail="Provedor não encontrado")
        cnpj = row[0]

        eventos = []

        cursor.execute(
            """
            SELECT ID_ENTRADA
            FROM CLB349328.PORTAL_COMPARTILHAMENTO_ENTRADA
            WHERE CNPJ = ?
            ORDER BY DATA_RECEBIMENTO DESC
            LIMIT 1
            """,
            [cnpj],
        )
        entrada_row = cursor.fetchone()

        if entrada_row:
            cursor.execute(
                """
                SELECT STATUS_ANTERIOR, STATUS_NOVO, USUARIO, OBSERVACAO, DATA_EVENTO
                FROM CLB349328.PORTAL_COMPARTILHAMENTO_HISTORICO_ENTRADA
                WHERE ID_ENTRADA = ?
                ORDER BY DATA_EVENTO ASC
                """,
                [entrada_row[0]],
            )
            for status_anterior, status_novo, usuario, observacao, data_evento in cursor.fetchall():
                titulo = f"{status_anterior} → {status_novo}" if status_anterior else str(status_novo)
                eventos.append({
                    "tipo": "ENTRADA",
                    "data": _processos_json_value(data_evento),
                    "titulo": titulo,
                    "descricao": observacao,
                    "usuario": usuario,
                    "id_processo": None,
                })

        cursor.execute(
            """
            SELECT ID_PROCESSO, NUMERO_PROTOCOLO
            FROM CLB349328.PORTAL_COMPARTILHAMENTO_PROCESSO
            WHERE ID_PROVEDOR = ?
            """,
            [id],
        )
        processos = cursor.fetchall()

        for id_processo, numero_protocolo in processos:
            cursor.execute(
                """
                SELECT E.NOME_ETAPA, J.STATUS_ETAPA, J.RESPONSAVEL_ATUAL, J.OBSERVACAO,
                       J.MOTIVO_RETORNO, J.DATA_ENTRADA_ETAPA
                FROM CLB349328.PORTAL_COMPARTILHAMENTO_JORNADA J
                INNER JOIN CLB349328.PORTAL_COMPARTILHAMENTO_ETAPA E
                    ON E.ID_ETAPA = J.ID_ETAPA
                WHERE J.ID_PROCESSO = ?
                  AND COALESCE(J.ATIVO, 'S') = 'S'
                ORDER BY J.DATA_ENTRADA_ETAPA ASC
                """,
                [id_processo],
            )
            for nome_etapa, status_etapa, responsavel, observacao, motivo_retorno, data_entrada in cursor.fetchall():
                eventos.append({
                    "tipo": "JORNADA",
                    "data": _processos_json_value(data_entrada),
                    "titulo": f"{numero_protocolo} - {nome_etapa} ({status_etapa})",
                    "descricao": motivo_retorno or observacao,
                    "usuario": responsavel,
                    "id_processo": id_processo,
                })

            cursor.execute(
                """
                SELECT DATA_CONTATO, MEIO_CONTATO, PESSOA_CONTATO, OBSERVACAO, USUARIO_REGISTRO
                FROM CLB349328.PORTAL_COMPARTILHAMENTO_CONTATO_PROCESSO
                WHERE ID_PROCESSO = ?
                ORDER BY DATA_CONTATO ASC
                """,
                [id_processo],
            )
            for data_contato, meio, pessoa, observacao, usuario in cursor.fetchall():
                titulo = f"{numero_protocolo} - Contato ({meio or 'N/D'})"
                if pessoa:
                    titulo += f" com {pessoa}"
                eventos.append({
                    "tipo": "CONTATO",
                    "data": _processos_json_value(data_contato),
                    "titulo": titulo,
                    "descricao": observacao,
                    "usuario": usuario,
                    "id_processo": id_processo,
                })

        eventos.sort(key=lambda e: e["data"] or "")

        return eventos

    except HTTPException:
        raise
    except Exception as e:
        raise HTTPException(status_code=500, detail=str(e))
    finally:
        if cursor:
            cursor.close()
        if conn:
            conn.close()


@router.post("/api/provedores/{id}/processos", response_model=dict)
def criar_processo_para_provedor_existente(id: int = Path(..., alias="id"), request: Request = None):
    """Abre um novo processo/PN para um provedor que já existe - sem passar
    pelo fluxo de Entrante (que é só pra CNPJ novo)."""
    conn = None
    cursor = None
    user = _usuario_do_request(request)

    try:
        conn = main.get_connection()
        cursor = conn.cursor()

        cursor.execute(
            "SELECT ID_PROVEDOR FROM CLB349328.PORTAL_COMPARTILHAMENTO_PROVEDOR WHERE ID_PROVEDOR = ?",
            [id],
        )
        if not cursor.fetchone():
            raise HTTPException(status_code=404, detail="Provedor não encontrado")

        id_processo, numero_protocolo = _criar_processo_para_provedor(cursor, id, user)
        conn.commit()

        return {
            "success": True,
            "id_provedor": id,
            "id_processo": id_processo,
            "numeroProtocolo": numero_protocolo,
            "mensagem": "Processo criado com sucesso.",
        }

    except HTTPException:
        if conn:
            conn.rollback()
        raise
    except Exception as e:
        if conn:
            conn.rollback()
        raise HTTPException(status_code=500, detail=str(e))
    finally:
        if cursor:
            cursor.close()
        if conn:
            conn.close()
