# -*- coding: utf-8 -*-
"""
Resultado Financeiro mensal: Faturamento, Custos e Receita Liquida.
Acompanhamento Meta x Realizado x REV (revisao/projecao), mensal e YTD.

DDL: sql/PORTAL_COMPARTILHAMENTO_RESULTADO_FINANCEIRO.sql
Consumido por app/(app)/resultados/resultadofinanceiro/page.tsx.

O acumulado YTD e o desvio (REALIZADO - META) NUNCA sao gravados - sao
sempre recalculados aqui a partir de META / REALIZADO / REV.
"""
import unicodedata
from typing import Any, Optional, List
from decimal import Decimal
from datetime import datetime, date

from fastapi import APIRouter, HTTPException, Query
from pydantic import BaseModel

import main

router = APIRouter()

SCHEMA = "CLB349328"
TB = f'"{SCHEMA}"."PORTAL_COMPARTILHAMENTO_RESULTADO_FINANCEIRO"'

INDICADORES = ["FATURAMENTO", "CUSTOS", "RECEITA_LIQUIDA"]
LABEL = {
    "FATURAMENTO": "Faturamento",
    "CUSTOS": "Custos",
    "RECEITA_LIQUIDA": "Receita Líquida",
}
MESES = ["Jan", "Fev", "Mar", "Abr", "Mai", "Jun", "Jul", "Ago", "Set", "Out", "Nov", "Dez"]


def _num(valor: Any) -> Any:
    if isinstance(valor, Decimal):
        return float(valor)
    if isinstance(valor, (datetime, date)):
        return valor.isoformat()
    return valor


def _normalizar_indicador(valor: Any) -> Optional[str]:
    t = unicodedata.normalize("NFD", str(valor or "")).upper()
    t = "".join(c for c in t if "A" <= c <= "Z")
    if t.startswith("FATURAMENTO") or t.startswith("RECEITABRUTA"):
        return "FATURAMENTO"
    if t.startswith("CUSTO") or t.startswith("DESPESA"):
        return "CUSTOS"
    if t.startswith("RECEITALIQUIDA") or t == "RL":
        return "RECEITA_LIQUIDA"
    return None


def _garantir_tabela(cursor) -> None:
    try:
        cursor.execute(f"SELECT COUNT(*) FROM {TB}")
        cursor.fetchone()
        return
    except Exception:
        pass
    cursor.execute(
        f"""
        CREATE COLUMN TABLE {TB}
        (
            "ID"         INTEGER CS_INT GENERATED BY DEFAULT AS IDENTITY (START WITH 1 INCREMENT BY 1) NOT NULL,
            "ANO"        INTEGER CS_INT NOT NULL,
            "MES"        INTEGER CS_INT NOT NULL,
            "INDICADOR"  NVARCHAR(30) NOT NULL,
            "META"       DECIMAL(18,2) DEFAULT 0,
            "REALIZADO"  DECIMAL(18,2),
            "REV"        DECIMAL(18,2),
            "MOEDA"      NVARCHAR(3) DEFAULT 'BRL',
            "OBSERVACAO" NVARCHAR(500),
            "CREATED_AT" LONGDATE CS_LONGDATE DEFAULT CURRENT_UTCTIMESTAMP,
            "CREATED_BY" NVARCHAR(120),
            "UPDATED_AT" LONGDATE CS_LONGDATE,
            "UPDATED_BY" NVARCHAR(120),
            PRIMARY KEY ("ID")
        )
        UNLOAD PRIORITY 5 AUTO MERGE
        """
    )
    try:
        cursor.execute(
            f'CREATE UNIQUE INDEX "IX_PORTAL_COMP_RESFIN_CHAVE" ON {TB} ("ANO", "MES", "INDICADOR")'
        )
    except Exception:
        pass


def _resumo(meta: float, realizado: Optional[float], rev: Optional[float]) -> dict:
    desvio = None if realizado is None else realizado - meta
    desvio_pct = None if (realizado is None or not meta) else desvio / meta
    return {"meta": meta, "realizado": realizado, "rev": rev, "desvio": desvio, "desvio_pct": desvio_pct}


def _montar_resposta(cursor, ano: int, mes_ref: Optional[int]) -> dict:
    cursor.execute(
        f'SELECT "MES", "INDICADOR", "META", "REALIZADO", "REV" FROM {TB} WHERE "ANO" = ?',
        [ano],
    )
    linhas = cursor.fetchall()
    por_chave = {(int(r[0]), r[1]): r for r in linhas}

    meses_fechados = max(
        [int(r[0]) for r in linhas if r[3] is not None] or [0]
    )
    ref = mes_ref if (mes_ref and 1 <= mes_ref <= 12) else (meses_fechados or 12)

    indicadores = []
    for indicador in INDICADORES:
        meta_ac = 0.0
        real_ac = 0.0
        rev_ac = 0.0
        tem_real = False
        meses = []
        for m in range(1, 13):
            row = por_chave.get((m, indicador))
            meta = float(row[2]) if row and row[2] is not None else 0.0
            realizado = float(row[3]) if row and row[3] is not None else None
            rev = float(row[4]) if row and row[4] is not None else None

            meta_ac += meta
            if realizado is not None:
                real_ac += realizado
                tem_real = True
            rev_ac += rev if rev is not None else (realizado if realizado is not None else meta)

            real_ytd = real_ac if tem_real else None
            desvio_ytd = None if real_ytd is None else real_ytd - meta_ac
            meses.append(
                {
                    "mes": m,
                    "meta": meta,
                    "realizado": realizado,
                    "rev": rev,
                    "meta_ytd": meta_ac,
                    "realizado_ytd": real_ytd,
                    "rev_ytd": rev_ac,
                    "desvio": None if realizado is None else realizado - meta,
                    "desvio_pct": None if (realizado is None or not meta) else (realizado - meta) / meta,
                    "desvio_ytd": desvio_ytd,
                    "desvio_ytd_pct": None if (real_ytd is None or not meta_ac) else desvio_ytd / meta_ac,
                }
            )

        m_ref = meses[ref - 1]
        indicadores.append(
            {
                "indicador": indicador,
                "label": LABEL[indicador],
                "meses": meses,
                "mensal": _resumo(m_ref["meta"], m_ref["realizado"], m_ref["rev"]),
                "ytd": _resumo(m_ref["meta_ytd"], m_ref["realizado_ytd"], m_ref["rev_ytd"]),
                "ano_total": {
                    "meta": meses[11]["meta_ytd"],
                    "realizado": real_ac if tem_real else None,
                    "rev": meses[11]["rev_ytd"],
                },
            }
        )

    return {"ano": ano, "mes_ref": ref, "meses_fechados": meses_fechados, "indicadores": indicadores}


def _upsert(cursor, ano: int, mes: int, indicador: str, campos: dict, usuario: Optional[str]) -> bool:
    cursor.execute(
        f'SELECT "ID" FROM {TB} WHERE "ANO" = ? AND "MES" = ? AND "INDICADOR" = ?',
        [ano, mes, indicador],
    )
    existente = cursor.fetchone()

    sets = []
    valores: List[Any] = []
    if "meta" in campos and campos["meta"] is not None:
        sets.append('"META" = ?')
        valores.append(float(campos["meta"]))
    if "realizado" in campos:
        sets.append('"REALIZADO" = ?')
        valores.append(None if campos["realizado"] is None else float(campos["realizado"]))
    if "rev" in campos:
        sets.append('"REV" = ?')
        valores.append(None if campos["rev"] is None else float(campos["rev"]))
    if "observacao" in campos:
        sets.append('"OBSERVACAO" = ?')
        valores.append(campos["observacao"] or None)

    if existente:
        if not sets:
            return False
        sets.append('"UPDATED_AT" = CURRENT_UTCTIMESTAMP')
        sets.append('"UPDATED_BY" = ?')
        valores.append(usuario or "api")
        valores.append(existente[0])
        cursor.execute(f'UPDATE {TB} SET {", ".join(sets)} WHERE "ID" = ?', valores)
        return False

    cursor.execute(
        f"""
        INSERT INTO {TB} ("ANO", "MES", "INDICADOR", "META", "REALIZADO", "REV", "CREATED_AT", "CREATED_BY")
        VALUES (?, ?, ?, ?, ?, ?, CURRENT_UTCTIMESTAMP, ?)
        """,
        [
            ano,
            mes,
            indicador,
            float(campos.get("meta") or 0),
            None if campos.get("realizado") is None else float(campos["realizado"]),
            None if campos.get("rev") is None else float(campos["rev"]),
            usuario or "api",
        ],
    )
    return True


class CelulaUpdate(BaseModel):
    ano: int
    mes: int
    indicador: str
    meta: Optional[float] = None
    realizado: Optional[float] = None
    rev: Optional[float] = None
    observacao: Optional[str] = None
    usuario: Optional[str] = None


class LinhaImport(BaseModel):
    ano: Optional[int] = None
    mes: int
    indicador: str
    meta: Optional[float] = None
    realizado: Optional[float] = None
    rev: Optional[float] = None


class ImportPayload(BaseModel):
    ano: Optional[int] = None
    linhas: List[LinhaImport]
    usuario: Optional[str] = None


@router.get("/api/resultado-financeiro/anos", response_model=List[int])
def listar_anos():
    conn = None
    cursor = None
    try:
        conn = main.get_connection()
        cursor = conn.cursor()
        _garantir_tabela(cursor)
        cursor.execute(f'SELECT DISTINCT "ANO" FROM {TB}')
        anos = {int(r[0]) for r in cursor.fetchall()}
        anos.add(date.today().year)
        return sorted(anos, reverse=True)
    finally:
        if cursor:
            cursor.close()
        if conn:
            conn.close()


@router.get("/api/resultado-financeiro")
def obter(ano: Optional[int] = Query(None), mes_ref: Optional[int] = Query(None)):
    conn = None
    cursor = None
    try:
        conn = main.get_connection()
        cursor = conn.cursor()
        _garantir_tabela(cursor)
        return _montar_resposta(cursor, ano or date.today().year, mes_ref)
    except Exception as e:
        raise HTTPException(status_code=500, detail=str(e))
    finally:
        if cursor:
            cursor.close()
        if conn:
            conn.close()


@router.put("/api/resultado-financeiro")
def atualizar_celula(dados: CelulaUpdate):
    indicador = _normalizar_indicador(dados.indicador)
    if not indicador:
        raise HTTPException(status_code=400, detail=f"indicador inválido (use {' / '.join(INDICADORES)})")
    if not (1 <= dados.mes <= 12):
        raise HTTPException(status_code=400, detail="mes deve ser de 1 a 12")

    conn = None
    cursor = None
    try:
        conn = main.get_connection()
        cursor = conn.cursor()
        _garantir_tabela(cursor)
        campos = dados.model_dump(exclude={"ano", "mes", "indicador", "usuario"}, exclude_unset=True)
        criada = _upsert(cursor, dados.ano, dados.mes, indicador, campos, dados.usuario)
        conn.commit()
        return {"success": True, "criada": criada, "dados": _montar_resposta(cursor, dados.ano, None)}
    except HTTPException:
        if conn:
            conn.rollback()
        raise
    except Exception as e:
        if conn:
            conn.rollback()
        raise HTTPException(status_code=500, detail=str(e))
    finally:
        if cursor:
            cursor.close()
        if conn:
            conn.close()


@router.post("/api/resultado-financeiro/importar")
def importar(payload: ImportPayload):
    if not payload.linhas:
        raise HTTPException(status_code=400, detail="nenhuma linha para importar")

    conn = None
    cursor = None
    try:
        conn = main.get_connection()
        cursor = conn.cursor()
        _garantir_tabela(cursor)

        criados = 0
        atualizados = 0
        ignorados = []
        anos_tocados = set()
        for i, linha in enumerate(payload.linhas):
            ano = linha.ano or payload.ano
            indicador = _normalizar_indicador(linha.indicador)
            if not ano or not (1 <= linha.mes <= 12) or not indicador:
                ignorados.append({"linha": i + 1, "motivo": "ano/mes/indicador inválidos"})
                continue
            campos = linha.model_dump(exclude={"ano", "mes", "indicador"}, exclude_unset=True)
            if not campos:
                ignorados.append({"linha": i + 1, "motivo": "sem valores (meta/realizado/rev)"})
                continue
            if _upsert(cursor, ano, linha.mes, indicador, campos, payload.usuario):
                criados += 1
            else:
                atualizados += 1
            anos_tocados.add(ano)

        conn.commit()
        ano_resp = payload.ano or (sorted(anos_tocados)[0] if anos_tocados else date.today().year)
        return {
            "success": True,
            "criados": criados,
            "atualizados": atualizados,
            "ignorados": ignorados,
            "total": len(payload.linhas),
            "dados": _montar_resposta(cursor, ano_resp, None),
        }
    except HTTPException:
        if conn:
            conn.rollback()
        raise
    except Exception as e:
        if conn:
            conn.rollback()
        raise HTTPException(status_code=500, detail=str(e))
    finally:
        if cursor:
            cursor.close()
        if conn:
            conn.close()
